//! # Profile Command Interface
//!
//! This header defines the `tml profile` command API for reading and
//! visualizing `.cpuprofile` files generated by the TML profiler.
//!
//! ## Subcommands
//!
//! | Subcommand              | Description                                    |
//! |-------------------------|------------------------------------------------|
//! | `flamegraph`            | Generate a flame graph from a .cpuprofile file |
//!
//! ## Output Formats
//!
//! | Flag              | Format                                              |
//! |-------------------|-----------------------------------------------------|
//! | (default)         | ASCII flame graph printed to stdout                 |
//! | `--ascii`         | ASCII flame graph printed to stdout                 |
//! | `-o output.svg`   | SVG flame graph written to file                     |

#pragma once

#include <string>

namespace tml::cli {

/**
 * @brief Main profile command dispatcher.
 *
 * Handles:
 *   tml profile flamegraph <input.cpuprofile> [--ascii] [-o output.svg]
 *
 * @param argc Argument count (starting from "profile")
 * @param argv Argument values (starting from "profile")
 * @param verbose Enable verbose output
 * @return 0 on success, non-zero on error
 */
int run_profile(int argc, char* argv[], bool verbose);

} // namespace tml::cli
