TML_MODULE("compiler")

//! # Dead Function Elimination Pass
//!
//! This pass removes functions that are never called from the module.
//!
//! ## Liveness Analysis
//!
//! | Step | Action                                |
//! |------|---------------------------------------|
//! | 1    | Build call graph from all calls       |
//! | 2    | Mark entry points (main, @test, etc.) |
//! | 3    | Propagate liveness through call graph |
//! | 4    | Remove functions not marked as live   |
//!
//! ## Protected Functions
//!
//! Some functions are always kept:
//! - main: Program entry point
//! - @test functions: Test entry points
//! - @bench functions: Benchmark entry points
//! - @export functions: FFI exports
//! - run_all_*: Benchmark/test runners

#include "mir/passes/dead_function_elimination.hpp"

#include "common.hpp"

#include <algorithm>
#include <cstdio>

namespace tml::mir {

// ============================================================================
// Helper Functions
// ============================================================================

// Check if a function is an entry point based on attributes.
//
// In a TML compilation unit (binary or test binary), the only roots are:
//   - `main` (the program entry point in a normal binary)
//   - `@test` / `@bench` / `@fuzz` / `@export` decorated functions
//     (test harness entry points and FFI exports)
//   - HTTP route handlers (`@Get` / `@Post` / etc.) — these are entry
//     points because the HTTP server reaches them through a route table
//     populated at startup, not through any direct call.
//
// `pub` (visibility) MUST NOT keep a function alive in this analysis.
// A `pub` function in a library crate is only meaningful if some entry
// point in the same compilation unit reaches it transitively. When the
// crate is compiled into a test binary, every `pub` function in the
// crate (e.g., the unused half of `lib/core/`) would otherwise survive
// LLVM lowering and bloat both compile time and binary size.
//
// (`extern` declarations have no body and are imported symbols — they
// must not be marked as roots either, otherwise the compiler would
// emit IR for unused FFI prototypes.)
static auto is_entry_point(const Function& func) -> bool {
    // Main function is always an entry point
    if (func.name == "main") {
        return true;
    }

    // Check for entry point attributes (only @test, @bench, @fuzz, @export).
    // Notably absent: "extern" (FFI declarations), "public" (visibility,
    // not an attribute on Function in the first place — left unchecked
    // historically and removed here to make the policy explicit).
    for (const auto& attr : func.attributes) {
        if (attr == "test" || attr == "bench" || attr == "fuzz" || attr == "export") {
            return true;
        }
    }

    // HTTP route-decorated functions are entry points (reached through
    // the route registration table populated at startup, not via a
    // direct call edge in MIR).
    if (func.route_info.has_value()) {
        return true;
    }

    // run_all_* functions are entry points (benchmark/test runners
    // generated by the test harness — referenced from the runtime).
    if (func.name.find("run_all_") == 0) {
        return true;
    }

    return false;
}

// ============================================================================
// DeadFunctionEliminationPass Implementation
// ============================================================================

auto DeadFunctionEliminationPass::run(Module& module) -> bool {
    stats_ = DeadFunctionStats{};
    live_functions_.clear();
    call_graph_.clear();

    stats_.functions_analyzed = module.functions.size();

    // Step 1: Build call graph
    build_call_graph(module);

    // Step 2: Mark entry points
    mark_entry_points(module);

    // Step 3: Propagate liveness
    propagate_liveness();

    // Step 4: Remove dead functions
    auto original_size = module.functions.size();

    // Count instructions in functions to be removed
    for (const auto& func : module.functions) {
        if (live_functions_.find(func.name) == live_functions_.end()) {
            stats_.instructions_removed += count_instructions(func);
        }
    }

    // Optional diagnostic dump (--dump-dead-functions). Emit BEFORE the
    // erase so we can print the bodies sizes side by side.
    if (tml::CompilerOptions::dump_dead_functions) {
        std::fprintf(stderr, "[dead-func-elim] module=%s analyzed=%zu live=%zu\n",
                     module.name.c_str(), stats_.functions_analyzed, live_functions_.size());

        // Sort kept and removed lists for stable output.
        std::vector<std::string> kept;
        std::vector<std::pair<std::string, size_t>> removed;
        for (const auto& func : module.functions) {
            if (live_functions_.find(func.name) != live_functions_.end()) {
                kept.push_back(func.name);
            } else {
                removed.emplace_back(func.name, count_instructions(func));
            }
        }
        std::sort(kept.begin(), kept.end());
        std::sort(removed.begin(), removed.end(), [](const auto& a, const auto& b) {
            // Largest functions first — these are the ones whose
            // removal matters most for codegen time.
            if (a.second != b.second)
                return a.second > b.second;
            return a.first < b.first;
        });

        std::fprintf(stderr, "[dead-func-elim] KEPT (%zu):\n", kept.size());
        for (const auto& name : kept) {
            std::fprintf(stderr, "  + %s\n", name.c_str());
        }
        std::fprintf(stderr, "[dead-func-elim] REMOVED (%zu):\n", removed.size());
        for (const auto& [name, insts] : removed) {
            std::fprintf(stderr, "  - %s (%zu insts)\n", name.c_str(), insts);
        }
        // Flush so the dump is visible even if later codegen stages take long
        // (or hang) — this is a diagnostic flag, correctness matters more than
        // avoiding a single flush cost.
        std::fflush(stderr);
    }

    // Remove dead functions
    module.functions.erase(std::remove_if(module.functions.begin(), module.functions.end(),
                                          [this](const Function& func) {
                                              return live_functions_.find(func.name) ==
                                                     live_functions_.end();
                                          }),
                           module.functions.end());

    stats_.functions_removed = original_size - module.functions.size();
    stats_.functions_kept = module.functions.size();

    return stats_.functions_removed > 0;
}

void DeadFunctionEliminationPass::build_call_graph(const Module& module) {
    for (const auto& func : module.functions) {
        // Ensure function is in the graph even if it calls nothing
        call_graph_[func.name];

        for (const auto& block : func.blocks) {
            for (const auto& inst : block.instructions) {
                // Check for direct calls
                if (auto* call = std::get_if<CallInst>(&inst.inst)) {
                    call_graph_[func.name].insert(call->func_name);
                }
                // Check for method calls
                else if (auto* mcall = std::get_if<MethodCallInst>(&inst.inst)) {
                    // Method calls use mangled names like "TypeName_method"
                    // Construct the full mangled name from receiver_type and method_name
                    std::string mangled_name = mcall->receiver_type + "__" + mcall->method_name;
                    call_graph_[func.name].insert(mangled_name);

                    // If devirtualized, also add the devirtualized target
                    if (mcall->devirt_info.has_value()) {
                        std::string devirt_target = mcall->devirt_info->original_class + "__" +
                                                    mcall->devirt_info->method_name;
                        call_graph_[func.name].insert(devirt_target);
                    }
                }
                // Check for function references (function pointers)
                // A ConstFuncRef means the function's address is taken, so it must be kept alive.
                else if (auto* const_inst = std::get_if<ConstantInst>(&inst.inst)) {
                    if (auto* func_ref = std::get_if<ConstFuncRef>(&const_inst->value)) {
                        call_graph_[func.name].insert(func_ref->func_name);
                    }
                }
                // Check for closure initializations — the closure body function
                // is referenced by name and must be kept alive.
                else if (auto* closure_init = std::get_if<ClosureInitInst>(&inst.inst)) {
                    call_graph_[func.name].insert(closure_init->func_name);
                }
            }
        }
    }
}

void DeadFunctionEliminationPass::mark_entry_points(const Module& module) {
    for (const auto& func : module.functions) {
        if (is_entry_point(func)) {
            live_functions_.insert(func.name);
            stats_.entry_points++;
        }
    }

    // Mark functions referenced by vtables (impl blocks) as live
    // These are called indirectly through dyn dispatch and must not be removed
    for (const auto& impl : module.impls) {
        for (const auto& [method_name, func_name] : impl.method_functions) {
            live_functions_.insert(func_name);
        }
    }

    // If no entry points found, keep all functions (library mode)
    if (live_functions_.empty()) {
        for (const auto& func : module.functions) {
            live_functions_.insert(func.name);
        }
    }
}

void DeadFunctionEliminationPass::propagate_liveness() {
    // Worklist algorithm: never iterate live_functions_ while inserting into it.
    // Inserting into unordered_set during iteration is UB (rehash invalidates iterators).
    std::vector<std::string> worklist(live_functions_.begin(), live_functions_.end());

    while (!worklist.empty()) {
        std::string func_name = std::move(worklist.back());
        worklist.pop_back();

        auto it = call_graph_.find(func_name);
        if (it == call_graph_.end()) {
            continue;
        }

        for (const auto& callee : it->second) {
            if (live_functions_.find(callee) == live_functions_.end()) {
                if (call_graph_.find(callee) != call_graph_.end()) {
                    live_functions_.insert(callee);
                    worklist.push_back(callee);
                }
            }
        }
    }
}

auto DeadFunctionEliminationPass::count_instructions(const Function& func) const -> size_t {
    size_t count = 0;
    for (const auto& block : func.blocks) {
        count += block.instructions.size();
        if (block.terminator) {
            count++;
        }
    }
    return count;
}

} // namespace tml::mir
