/* Generated by TML Compiler */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* TML Runtime Types */
typedef struct { const char* data; size_t len; } tml_str_t;
typedef struct { void* data; size_t len; } tml_slice_t;

/* TML Runtime Functions */
static void tml_print(tml_str_t s) {
    fwrite(s.data, 1, s.len, stdout);
    putchar('\n');
}

static tml_str_t tml_str_from_literal(const char* s) {
    return (tml_str_t){ .data = s, .len = strlen(s) };
}

/* Forward Declarations */
void tml_main(void);
int32_t tml_add(int32_t x, int32_t y);
typedef struct tml_Point tml_Point;

/* Type Definitions */
struct tml_Point {
    int32_t x;
    int32_t y;
};


/* Function Definitions */
/* func main */
void tml_main(void) {
    int32_t message = tml_str_from_literal("Hello, World!");
    tml_print(message);
}

/* func add */
int32_t tml_add(int32_t x, int32_t y) {
    return (x + y);
}


/* Entry Point */
int main(int argc, char** argv) {
    tml_main();
    return 0;
}
