#pragma once

//! Centralized header for all MIR optimization passes
//! This header aggregates all 44+ pass includes to reduce compilation overhead
//! in mir_pass.cpp (was 54 direct includes, now just 1)

// Functional optimization passes
#include "mir/passes/adce.hpp"
#include "mir/passes/block_merge.hpp"
#include "mir/passes/bounds_check_elimination.hpp"
#include "mir/passes/common_subexpression_elimination.hpp"
#include "mir/passes/const_hoist.hpp"
#include "mir/passes/constant_folding.hpp"
#include "mir/passes/constant_propagation.hpp"
#include "mir/passes/copy_propagation.hpp"
#include "mir/passes/dead_arg_elim.hpp"
#include "mir/passes/dead_code_elimination.hpp"
#include "mir/passes/dead_function_elimination.hpp"
#include "mir/passes/destination_propagation.hpp"
#include "mir/passes/early_cse.hpp"
#include "mir/passes/gvn.hpp"
#include "mir/passes/inlining.hpp"
#include "mir/passes/inst_simplify.hpp"
#include "mir/passes/jump_threading.hpp"
#include "mir/passes/licm.hpp"
#include "mir/passes/load_store_opt.hpp"
#include "mir/passes/loop_rotate.hpp"
#include "mir/passes/loop_unroll.hpp"
#include "mir/passes/match_simplify.hpp"
#include "mir/passes/mem2reg.hpp"
#include "mir/passes/merge_returns.hpp"
#include "mir/passes/narrowing.hpp"
#include "mir/passes/normalize_array_len.hpp"
#include "mir/passes/peephole.hpp"
#include "mir/passes/pgo.hpp"
#include "mir/passes/reassociate.hpp"
#include "mir/passes/remove_unneeded_drops.hpp"
#include "mir/passes/simplify_cfg.hpp"
#include "mir/passes/simplify_select.hpp"
#include "mir/passes/sinking.hpp"
#include "mir/passes/sroa.hpp"
#include "mir/passes/strength_reduction.hpp"
#include "mir/passes/tail_call.hpp"
#include "mir/passes/unreachable_code_elimination.hpp"
#include "mir/passes/vectorization.hpp"

// OOP optimization passes
#include "mir/passes/alias_analysis.hpp"
#include "mir/passes/batch_destruction.hpp"
#include "mir/passes/builder_opt.hpp"
#include "mir/passes/constructor_fusion.hpp"
#include "mir/passes/dead_method_elimination.hpp"
#include "mir/passes/destructor_hoist.hpp"
#include "mir/passes/devirtualization.hpp"
#include "mir/passes/escape_analysis.hpp"
#include "mir/passes/ipo.hpp"
#include "mir/passes/loop_opts.hpp"
#include "mir/passes/rvo.hpp"
