//! # LLVM IR Generator - Runtime Declarations
//!
//! This file emits the target header and runtime type/function declarations.
//! Module import codegen is in runtime_modules.cpp.
//!
//! ## Emitted Sections
//!
//! | Method                         | Emits                         |
//! |--------------------------------|-------------------------------|
//! | `emit_header`                  | Target triple, comments       |
//! | `emit_runtime_decls`           | Struct types, C functions     |
//!
//! ## Runtime Types
//!
//! | Type            | Layout              | Purpose             |
//! |-----------------|---------------------|---------------------|
//! | `%struct.tml_str` | `{ ptr, i64 }`    | String slice        |
//! | `%struct.File`  | `{ ptr }`           | File handle         |
//! | `%struct.Path`  | `{ ptr }`           | Path string         |
//! | `%struct.Ordering` | `{ i32 }`        | Comparison result   |
//!
//! ## External Functions
//!
//! Declares C standard library functions: printf, puts, malloc, free, exit.

#include "codegen/llvm/llvm_ir_gen.hpp"
#include "lexer/lexer.hpp"
#include "lexer/source.hpp"
#include "parser/parser.hpp"

#include <filesystem>
#include <unordered_set>

namespace tml::codegen {

void LLVMIRGen::emit_header() {
    emit_line("; Generated by TML Compiler");
    emit_line("target triple = \"" + options_.target_triple + "\"");
    emit_line("");
}

void LLVMIRGen::emit_runtime_decls() {
    // String type: { ptr, i64 } (pointer to data, length)
    emit_line("; Runtime type declarations");
    emit_line("%struct.tml_str = type { ptr, i64 }");

    // File I/O types (from std::file)
    emit_line("%struct.File = type { ptr }"); // handle field
    struct_types_["File"] = "%struct.File";
    struct_fields_["File"] = {{"handle", 0, "ptr", types::make_ptr(types::make_unit())}};
    emit_line("%struct.Path = type { ptr }"); // path string field
    struct_types_["Path"] = "%struct.Path";
    struct_fields_["Path"] = {{"path", 0, "ptr", types::make_ptr(types::make_unit())}};

    // Core comparison type (core::cmp)
    // Ordering is a simple enum: Less=0, Equal=1, Greater=2
    emit_line("%struct.Ordering = type { i32 }");
    struct_types_["Ordering"] = "%struct.Ordering";
    struct_fields_["Ordering"] = {{"value", 0, "i32", types::make_i32()}};

    // HashMapIter type for iterating over HashMap entries
    emit_line("%struct.HashMapIter = type { ptr }");
    struct_types_["HashMapIter"] = "%struct.HashMapIter";
    struct_fields_["HashMapIter"] = {{"handle", 0, "ptr", types::make_ptr(types::make_unit())}};

    // Note: Buffer type removed — now pure TML (see lib/std/src/collections/buffer.tml)

    // Thread types (from std::thread) - needed for @extern function declarations
    emit_line("%struct.RawThread = type { i64 }"); // _handle: U64
    struct_types_["RawThread"] = "%struct.RawThread";
    struct_fields_["RawThread"] = {
        {"_handle", 0, "i64", types::make_primitive(types::PrimitiveKind::U64)}};
    emit_line("%struct.RawPtr = type { i64 }"); // addr: I64
    struct_types_["RawPtr"] = "%struct.RawPtr";
    struct_fields_["RawPtr"] = {{"addr", 0, "i64", types::make_i64()}};
    emit_line("");

    // External C functions
    emit_line("; External function declarations");
    emit_line("declare i32 @printf(ptr, ...)");
    emit_line("declare i32 @puts(ptr)");
    emit_line("declare i32 @putchar(i32)");
    emit_line("declare ptr @malloc(i64)");
    emit_line("declare void @free(ptr)");
    emit_line("declare void @exit(i32) noreturn");
    emit_line("declare i64 @strlen(ptr)");
    emit_line("");

    // LLVM intrinsics for optimized codegen
    emit_line("; LLVM intrinsics");
    emit_line("declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)");
    emit_line("declare void @llvm.memmove.p0.p0.i64(ptr, ptr, i64, i1)");
    emit_line("declare void @llvm.memset.p0.i64(ptr, i8, i64, i1)");
    emit_line("declare void @llvm.assume(i1) nounwind");
    emit_line("");

    // TML runtime functions
    emit_line("; TML runtime functions");
    emit_line("declare void @panic(ptr) noreturn");
    emit_line("declare void @assert_tml_loc(i32, ptr, ptr, i32) noreturn");
    emit_line("");

    // Panic catching for @should_panic tests
    // Uses a callback approach: pass function pointer to tml_run_should_panic()
    emit_line("; Panic catching (for @should_panic tests)");
    emit_line("declare i32 @tml_run_should_panic(ptr)");
    emit_line("declare ptr @tml_get_panic_message()");
    emit_line("declare i32 @tml_panic_message_contains(ptr)");
    emit_line("");

    // Backtrace support (--backtrace flag enables printing stack trace on panic)
    emit_line("; Backtrace support");
    emit_line("declare void @tml_enable_backtrace_on_panic()");
    emit_line("");

    // Note: TML test assertions are now provided by the test module's TML code
    // They call panic() internally and don't need external declarations
    emit_line("");

    // TML code coverage functions (only when coverage is enabled)
    if (options_.coverage_enabled) {
        emit_line("; TML code coverage");
        emit_line("declare void @tml_cover_func(ptr)");
        emit_line("declare void @print_coverage_report()");
        emit_line("declare void @write_coverage_json(ptr)");
        emit_line("declare void @write_coverage_html(ptr)");
        emit_line("");
        // Register in declared_externals_ to prevent duplicate declarations
        // when test::coverage module is imported (it has @extern("tml_cover_func"))
        declared_externals_.insert("tml_cover_func");
        declared_externals_.insert("print_coverage_report");
        declared_externals_.insert("write_coverage_json");
        declared_externals_.insert("write_coverage_html");
    }

    // Debug intrinsics (for DWARF debug info)
    if (options_.emit_debug_info) {
        emit_line("; Debug intrinsics");
        emit_line("declare void @llvm.dbg.declare(metadata, metadata, metadata) nounwind readnone");
        emit_line("declare void @llvm.dbg.value(metadata, metadata, metadata) nounwind readnone");
        emit_line("");
    }

    // LLVM instrumentation profile intrinsic (for source-based coverage)
    if (options_.llvm_source_coverage) {
        emit_line("; LLVM instrumentation profile intrinsics (source-based coverage)");
        emit_line("declare void @llvm.instrprof.increment(ptr, i64, i32, i32) #1");
        emit_line("");
    }

    // Stack save/restore intrinsics (for loop alloca cleanup)
    emit_line("; Stack management intrinsics");
    emit_line("declare ptr @llvm.stacksave() nounwind");
    emit_line("declare void @llvm.stackrestore(ptr) nounwind");
    emit_line("");

    // Lifetime intrinsics (for stack slot optimization)
    emit_line("; Lifetime intrinsics for stack optimization");
    emit_line("declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture) nounwind");
    emit_line("declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture) nounwind");
    emit_line("");

    // Threading runtime declarations
    emit_line("; Threading runtime (tml_runtime.c)");
    emit_line("declare ptr @thread_spawn(ptr, ptr)");
    emit_line("declare void @thread_join(ptr)");
    emit_line("declare void @thread_yield()");
    emit_line("declare void @thread_sleep(i32)");
    emit_line("declare i32 @thread_id()");
    emit_line("");

    // I/O functions - all check output suppression flag
    emit_line("; I/O functions (check output suppression)");
    emit_line("declare void @print(ptr)");
    emit_line("declare void @println(ptr)");
    emit_line("declare void @print_i32(i32)");
    emit_line("declare void @print_i64(i64)");
    emit_line("declare void @print_f32(float)");
    emit_line("declare void @print_f64(double)");
    emit_line("declare void @print_bool(i32)");
    emit_line("declare void @print_char(i32)");
    emit_line("");

    // NOTE: Math functions moved to core::math module
    // Import with: use core::math

    // NOTE: Assertion functions moved to test module
    // Import with: use test
    emit_line("; Black box (prevent optimization)");
    emit_line("declare i32 @black_box_i32(i32)");
    emit_line("declare i64 @black_box_i64(i64)");
    emit_line("declare double @black_box_f64(double)");
    emit_line("; SIMD operations (auto-vectorized)");
    emit_line("declare i64 @simd_sum_i32(ptr, i64)");
    emit_line("declare i64 @simd_sum_i64(ptr, i64)");
    emit_line("declare double @simd_sum_f64(ptr, i64)");
    emit_line("declare double @simd_dot_f64(ptr, ptr, i64)");
    emit_line("declare void @simd_fill_i32(ptr, i32, i64)");
    emit_line("declare void @simd_add_i32(ptr, ptr, ptr, i64)");
    emit_line("declare void @simd_mul_i32(ptr, ptr, ptr, i64)");
    emit_line("");

    // Float functions
    emit_line("; Float functions");
    emit_line("declare ptr @float_to_fixed(double, i32)");
    emit_line("declare ptr @float_to_precision(double, i32)");
    emit_line("declare ptr @float_to_string(double)");
    emit_line("declare ptr @f64_to_string(double)"); // F64.to_string() method
    emit_line("declare ptr @f32_to_string(float)");  // F32.to_string() method
    emit_line("declare ptr @float_to_exp(double, i32)");
    emit_line("declare ptr @f64_to_string_precision(double, i64)");
    emit_line("declare ptr @f32_to_string_precision(float, i64)");
    emit_line("declare ptr @f64_to_exp_string(double, i32)");
    emit_line("declare ptr @f32_to_exp_string(float, i32)");
    emit_line("declare i32 @f64_is_nan(double)");
    emit_line("declare i32 @f64_is_infinite(double)");
    emit_line("declare i32 @f32_is_nan(float)");
    emit_line("declare i32 @f32_is_infinite(float)");
    emit_line("declare double @int_to_float(i32)");
    emit_line("declare double @i64_to_float(i64)");
    emit_line("declare i32 @float_to_int(double)");
    emit_line("declare i64 @float_to_i64(double)");
    emit_line("declare i32 @float_round(double)");
    emit_line("declare i32 @float_floor(double)");
    emit_line("declare i32 @float_ceil(double)");
    emit_line("declare double @float_abs(double)");
    emit_line("declare double @float_sqrt(double)");
    emit_line("declare double @float_pow(double, i32)");
    emit_line("");

    // Integer to string conversion
    emit_line("; Integer to string");
    emit_line("declare ptr @i32_to_string(i32)");
    emit_line("declare ptr @i64_to_string(i64)");
    emit_line("declare ptr @bool_to_string(i1)");
    emit_line("");

    // Integer formatting (binary, octal, hex)
    emit_line("; Integer formatting");
    emit_line("declare ptr @i64_to_binary_str(i64)");
    emit_line("declare ptr @i64_to_octal_str(i64)");
    emit_line("declare ptr @i64_to_lower_hex_str(i64)");
    emit_line("declare ptr @i64_to_upper_hex_str(i64)");
    emit_line("");

    // Overloaded abs functions
    emit_line("; Overloaded abs");
    emit_line("declare i32 @abs_i32(i32)");
    emit_line("declare double @abs_f64(double)");
    emit_line("");

    // Bit manipulation runtime declarations
    emit_line("; Bit manipulation runtime");
    emit_line("declare i32 @float32_bits(float)");
    emit_line("declare float @float32_from_bits(i32)");
    emit_line("declare i64 @float64_bits(double)");
    emit_line("declare double @float64_from_bits(i64)");
    emit_line("");

    // Special float value runtime declarations
    emit_line("; Special float values runtime");
    emit_line("declare double @infinity(i32)");
    emit_line("declare double @nan()");
    emit_line("declare i32 @is_inf(double, i32)");
    emit_line("declare i32 @is_nan(double)");
    emit_line("");

    // Nextafter runtime declarations
    emit_line("; Nextafter runtime");
    emit_line("declare double @nextafter(double, double)");
    emit_line("declare float @nextafter32(float, float)");
    emit_line("");

    // Channel runtime declarations
    emit_line("; Channel runtime (Go-style)");
    emit_line("declare ptr @channel_create()");
    emit_line("declare i32 @channel_send(ptr, i32)");
    emit_line("declare i32 @channel_recv(ptr, ptr)");
    emit_line("declare i32 @channel_try_send(ptr, i32)");
    emit_line("declare i32 @channel_try_recv(ptr, ptr)");
    emit_line("declare void @channel_close(ptr)");
    emit_line("declare void @channel_destroy(ptr)");
    emit_line("declare i32 @channel_len(ptr)");
    emit_line("");

    // Mutex runtime declarations
    emit_line("; Mutex runtime");
    emit_line("declare ptr @mutex_create()");
    emit_line("declare void @mutex_lock(ptr)");
    emit_line("declare void @mutex_unlock(ptr)");
    emit_line("declare i32 @mutex_try_lock(ptr)");
    emit_line("declare void @mutex_destroy(ptr)");
    emit_line("");

    // WaitGroup runtime declarations
    emit_line("; WaitGroup runtime (Go-style)");
    emit_line("declare ptr @waitgroup_create()");
    emit_line("declare void @waitgroup_add(ptr, i32)");
    emit_line("declare void @waitgroup_done(ptr)");
    emit_line("declare void @waitgroup_wait(ptr)");
    emit_line("declare void @waitgroup_destroy(ptr)");
    emit_line("");

    // Atomic counter runtime declarations
    emit_line("; Atomic counter runtime");
    emit_line("declare ptr @atomic_counter_create(i32)");
    emit_line("declare i32 @atomic_counter_inc(ptr)");
    emit_line("declare i32 @atomic_counter_dec(ptr)");
    emit_line("declare i32 @atomic_counter_get(ptr)");
    emit_line("declare void @atomic_counter_set(ptr, i32)");
    emit_line("declare void @atomic_counter_destroy(ptr)");
    emit_line("");

    // Typed atomic operations runtime (also declared in sync.tml with @extern)
    // We declare them here AND register in declared_externals_ so that:
    // 1. Tests using atomics directly work without importing sync.tml
    // 2. When sync.tml is imported, its @extern won't cause redefinition errors
    emit_line("; Typed atomic operations runtime");
    emit_line("declare i32 @atomic_fetch_add_i32(ptr, i32)");
    declared_externals_.insert("atomic_fetch_add_i32");
    emit_line("declare i32 @atomic_fetch_sub_i32(ptr, i32)");
    declared_externals_.insert("atomic_fetch_sub_i32");
    emit_line("declare i32 @atomic_load_i32(ptr)");
    declared_externals_.insert("atomic_load_i32");
    emit_line("declare void @atomic_store_i32(ptr, i32)");
    declared_externals_.insert("atomic_store_i32");
    emit_line("declare i32 @atomic_compare_exchange_i32(ptr, i32, i32)");
    declared_externals_.insert("atomic_compare_exchange_i32");
    emit_line("declare i32 @atomic_swap_i32(ptr, i32)");
    declared_externals_.insert("atomic_swap_i32");
    emit_line("declare void @atomic_fence()");
    declared_externals_.insert("atomic_fence");
    emit_line("declare void @atomic_fence_acquire()");
    declared_externals_.insert("atomic_fence_acquire");
    emit_line("declare void @atomic_fence_release()");
    declared_externals_.insert("atomic_fence_release");
    emit_line("");

    // Note: List and HashMap runtime declarations removed — now pure TML
    // (see lib/std/src/collections/list.tml, hashmap.tml)

    // Note: Buffer runtime declarations removed — now pure TML

    // File I/O runtime declarations
    // Register in declared_externals_ to prevent duplicate declarations from @extern modules
    emit_line("; File I/O runtime");
    emit_line("declare ptr @file_open_read(ptr)");
    declared_externals_.insert("file_open_read");
    emit_line("declare ptr @file_open_write(ptr)");
    declared_externals_.insert("file_open_write");
    emit_line("declare ptr @file_open_append(ptr)");
    declared_externals_.insert("file_open_append");
    emit_line("declare void @file_close(ptr)");
    declared_externals_.insert("file_close");
    emit_line("declare i1 @file_is_open(ptr)");
    declared_externals_.insert("file_is_open");
    emit_line("declare ptr @file_read_line(ptr)");
    declared_externals_.insert("file_read_line");
    emit_line("declare i1 @file_write_str(ptr, ptr)");
    declared_externals_.insert("file_write_str");
    emit_line("declare i64 @file_size(ptr)");
    declared_externals_.insert("file_size");
    emit_line("declare ptr @file_read_all(ptr)");
    declared_externals_.insert("file_read_all");
    emit_line("declare i1 @file_write_all(ptr, ptr)");
    declared_externals_.insert("file_write_all");
    emit_line("declare i1 @file_append_all(ptr, ptr)");
    declared_externals_.insert("file_append_all");
    emit_line("declare i1 @file_flush(ptr)");
    declared_externals_.insert("file_flush");
    emit_line("");

    // Register file I/O functions in functions_ map for lowlevel calls from module functions
    functions_["file_open_read"] = FuncInfo{"@file_open_read", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["file_open_write"] = FuncInfo{"@file_open_write", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["file_open_append"] = FuncInfo{"@file_open_append", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["file_close"] = FuncInfo{"@file_close", "void (ptr)", "void", {"ptr"}};
    functions_["file_is_open"] = FuncInfo{"@file_is_open", "i1 (ptr)", "i1", {"ptr"}};
    functions_["file_read_line"] = FuncInfo{"@file_read_line", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["file_write_str"] =
        FuncInfo{"@file_write_str", "i1 (ptr, ptr)", "i1", {"ptr", "ptr"}};
    functions_["file_size"] = FuncInfo{"@file_size", "i64 (ptr)", "i64", {"ptr"}};
    functions_["file_read_all"] = FuncInfo{"@file_read_all", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["file_write_all"] =
        FuncInfo{"@file_write_all", "i1 (ptr, ptr)", "i1", {"ptr", "ptr"}};
    functions_["file_append_all"] =
        FuncInfo{"@file_append_all", "i1 (ptr, ptr)", "i1", {"ptr", "ptr"}};
    functions_["file_flush"] = FuncInfo{"@file_flush", "i1 (ptr)", "i1", {"ptr"}};

    // Log runtime declarations (matches runtime/log.c)
    emit_line("; Log runtime");
    emit_line("declare void @rt_log_msg(i32, ptr, ptr)");
    declared_externals_.insert("rt_log_msg");
    emit_line("declare void @rt_log_set_level(i32)");
    declared_externals_.insert("rt_log_set_level");
    emit_line("declare i32 @rt_log_get_level()");
    declared_externals_.insert("rt_log_get_level");
    emit_line("declare i32 @rt_log_enabled(i32)");
    declared_externals_.insert("rt_log_enabled");
    emit_line("");

    // Phase 4.4: Advanced log runtime declarations
    emit_line("declare void @rt_log_set_filter(ptr)");
    declared_externals_.insert("rt_log_set_filter");
    emit_line("declare i32 @rt_log_module_enabled(i32, ptr)");
    declared_externals_.insert("rt_log_module_enabled");
    emit_line("declare void @rt_log_structured(i32, ptr, ptr, ptr)");
    declared_externals_.insert("rt_log_structured");
    emit_line("declare void @rt_log_set_format(i32)");
    declared_externals_.insert("rt_log_set_format");
    emit_line("declare i32 @rt_log_get_format()");
    declared_externals_.insert("rt_log_get_format");
    emit_line("declare i32 @rt_log_open_file(ptr)");
    declared_externals_.insert("rt_log_open_file");
    emit_line("declare void @rt_log_close_file()");
    declared_externals_.insert("rt_log_close_file");
    emit_line("declare i32 @rt_log_init_from_env()");
    declared_externals_.insert("rt_log_init_from_env");
    emit_line("");

    // Register log functions in functions_ map for lowlevel calls
    functions_["rt_log_msg"] =
        FuncInfo{"@rt_log_msg", "void (i32, ptr, ptr)", "void", {"i32", "ptr", "ptr"}};
    functions_["rt_log_set_level"] = FuncInfo{"@rt_log_set_level", "void (i32)", "void", {"i32"}};
    functions_["rt_log_get_level"] = FuncInfo{"@rt_log_get_level", "i32 ()", "i32", {}};
    functions_["rt_log_enabled"] = FuncInfo{"@rt_log_enabled", "i32 (i32)", "i32", {"i32"}};
    // Phase 4.4 function registrations
    functions_["rt_log_set_filter"] = FuncInfo{"@rt_log_set_filter", "void (ptr)", "void", {"ptr"}};
    functions_["rt_log_module_enabled"] =
        FuncInfo{"@rt_log_module_enabled", "i32 (i32, ptr)", "i32", {"i32", "ptr"}};
    functions_["rt_log_structured"] = FuncInfo{
        "@rt_log_structured", "void (i32, ptr, ptr, ptr)", "void", {"i32", "ptr", "ptr", "ptr"}};
    functions_["rt_log_set_format"] = FuncInfo{"@rt_log_set_format", "void (i32)", "void", {"i32"}};
    functions_["rt_log_get_format"] = FuncInfo{"@rt_log_get_format", "i32 ()", "i32", {}};
    functions_["rt_log_open_file"] = FuncInfo{"@rt_log_open_file", "i32 (ptr)", "i32", {"ptr"}};
    functions_["rt_log_close_file"] = FuncInfo{"@rt_log_close_file", "void ()", "void", {}};
    functions_["rt_log_init_from_env"] = FuncInfo{"@rt_log_init_from_env", "i32 ()", "i32", {}};

    // Path utilities runtime declarations
    // Register in declared_externals_ to prevent duplicate declarations from @extern modules
    emit_line("; Path utilities runtime");
    emit_line("declare i1 @path_exists(ptr)");
    declared_externals_.insert("path_exists");
    emit_line("declare i1 @path_is_file(ptr)");
    declared_externals_.insert("path_is_file");
    emit_line("declare i1 @path_is_dir(ptr)");
    declared_externals_.insert("path_is_dir");
    emit_line("declare i1 @path_create_dir(ptr)");
    declared_externals_.insert("path_create_dir");
    emit_line("declare i1 @path_create_dir_all(ptr)");
    declared_externals_.insert("path_create_dir_all");
    emit_line("declare i1 @path_remove(ptr)");
    declared_externals_.insert("path_remove");
    emit_line("declare i1 @path_remove_dir(ptr)");
    declared_externals_.insert("path_remove_dir");
    emit_line("declare i1 @path_rename(ptr, ptr)");
    declared_externals_.insert("path_rename");
    emit_line("declare i1 @path_copy(ptr, ptr)");
    declared_externals_.insert("path_copy");
    emit_line("declare ptr @path_join(ptr, ptr)");
    declared_externals_.insert("path_join");
    emit_line("declare ptr @path_parent(ptr)");
    declared_externals_.insert("path_parent");
    emit_line("declare ptr @path_filename(ptr)");
    declared_externals_.insert("path_filename");
    emit_line("declare ptr @path_extension(ptr)");
    declared_externals_.insert("path_extension");
    emit_line("declare ptr @path_absolute(ptr)");
    declared_externals_.insert("path_absolute");

    // Register path functions in functions_ map for lowlevel calls from module functions
    // (e.g., Dir::create calls lowlevel { path_create_dir(path) })
    functions_["path_exists"] = FuncInfo{"@path_exists", "i1 (ptr)", "i1", {"ptr"}};
    functions_["path_is_file"] = FuncInfo{"@path_is_file", "i1 (ptr)", "i1", {"ptr"}};
    functions_["path_is_dir"] = FuncInfo{"@path_is_dir", "i1 (ptr)", "i1", {"ptr"}};
    functions_["path_create_dir"] = FuncInfo{"@path_create_dir", "i1 (ptr)", "i1", {"ptr"}};
    functions_["path_create_dir_all"] = FuncInfo{"@path_create_dir_all", "i1 (ptr)", "i1", {"ptr"}};
    functions_["path_remove"] = FuncInfo{"@path_remove", "i1 (ptr)", "i1", {"ptr"}};
    functions_["path_remove_dir"] = FuncInfo{"@path_remove_dir", "i1 (ptr)", "i1", {"ptr"}};
    functions_["path_rename"] = FuncInfo{"@path_rename", "i1 (ptr, ptr)", "i1", {"ptr", "ptr"}};
    functions_["path_copy"] = FuncInfo{"@path_copy", "i1 (ptr, ptr)", "i1", {"ptr", "ptr"}};
    functions_["path_join"] = FuncInfo{"@path_join", "ptr (ptr, ptr)", "ptr", {"ptr", "ptr"}};
    functions_["path_parent"] = FuncInfo{"@path_parent", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["path_filename"] = FuncInfo{"@path_filename", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["path_extension"] = FuncInfo{"@path_extension", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["path_absolute"] = FuncInfo{"@path_absolute", "ptr (ptr)", "ptr", {"ptr"}};
    emit_line("");

    // Glob runtime declarations
    emit_line("; Glob runtime");
    emit_line("declare ptr @glob_match(ptr, ptr)");
    declared_externals_.insert("glob_match");
    emit_line("declare ptr @glob_result_next(ptr)");
    declared_externals_.insert("glob_result_next");
    emit_line("declare i64 @glob_result_count(ptr)");
    declared_externals_.insert("glob_result_count");
    emit_line("declare void @glob_result_free(ptr)");
    declared_externals_.insert("glob_result_free");
    emit_line("declare i1 @glob_pattern_matches(ptr, ptr)");
    declared_externals_.insert("glob_pattern_matches");

    functions_["glob_match"] = FuncInfo{"@glob_match", "ptr (ptr, ptr)", "ptr", {"ptr", "ptr"}};
    functions_["glob_result_next"] = FuncInfo{"@glob_result_next", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["glob_result_count"] = FuncInfo{"@glob_result_count", "i64 (ptr)", "i64", {"ptr"}};
    functions_["glob_result_free"] = FuncInfo{"@glob_result_free", "void (ptr)", "void", {"ptr"}};
    functions_["glob_pattern_matches"] =
        FuncInfo{"@glob_pattern_matches", "i1 (ptr, ptr)", "i1", {"ptr", "ptr"}};
    emit_line("");

    // String utilities (matches runtime/string.c)
    emit_line("; String utilities");
    emit_line("declare i32 @str_len(ptr)");
    emit_line("declare i32 @str_eq(ptr, ptr)");
    emit_line("declare i32 @str_hash(ptr)");
    emit_line("declare ptr @str_concat(ptr, ptr)");
    emit_line("declare ptr @str_concat_opt(ptr, ptr)");         // O(1) amortized
    emit_line("declare ptr @str_concat_3(ptr, ptr, ptr)");      // Fused 3-string concat
    emit_line("declare ptr @str_concat_4(ptr, ptr, ptr, ptr)"); // Fused 4-string concat
    emit_line("declare ptr @str_substring(ptr, i32, i32)");
    emit_line("declare ptr @str_slice(ptr, i64, i64)");
    emit_line("declare i32 @str_contains(ptr, ptr)");
    emit_line("declare i32 @str_starts_with(ptr, ptr)");
    emit_line("declare i32 @str_ends_with(ptr, ptr)");
    emit_line("declare ptr @str_to_upper(ptr)");
    emit_line("declare ptr @str_to_lower(ptr)");
    emit_line("declare ptr @str_trim(ptr)");
    emit_line("declare ptr @str_trim_start(ptr)");
    emit_line("declare ptr @str_trim_end(ptr)");
    emit_line("declare i32 @str_char_at(ptr, i32)");
    emit_line("declare i64 @str_find(ptr, ptr)");
    emit_line("declare i64 @str_rfind(ptr, ptr)");
    emit_line("declare i64 @str_parse_i64(ptr)");
    emit_line("declare ptr @str_replace(ptr, ptr, ptr)");
    emit_line("declare ptr @str_replace_first(ptr, ptr, ptr)");
    emit_line("declare ptr @str_split(ptr, ptr)");
    emit_line("declare ptr @str_split_whitespace(ptr)");
    emit_line("declare ptr @str_lines(ptr)");
    emit_line("declare ptr @str_chars(ptr)");
    emit_line("declare ptr @str_repeat(ptr, i32)");
    emit_line("declare i32 @str_parse_i32(ptr)");
    emit_line("declare double @str_parse_f64(ptr)");
    emit_line("declare ptr @str_join(ptr, ptr)");
    emit_line("declare ptr @str_as_bytes(ptr)");
    emit_line("declare ptr @i64_to_str(i64)");
    emit_line("declare ptr @f64_to_str(double)");
    emit_line("");

    // Char utilities (matches runtime/string.c)
    emit_line("; Char utilities");
    emit_line("declare i32 @char_is_alphabetic(i32)");
    emit_line("declare i32 @char_is_numeric(i32)");
    emit_line("declare i32 @char_is_alphanumeric(i32)");
    emit_line("declare i32 @char_is_whitespace(i32)");
    emit_line("declare i32 @char_is_uppercase(i32)");
    emit_line("declare i32 @char_is_lowercase(i32)");
    emit_line("declare i32 @char_is_ascii(i32)");
    emit_line("declare i32 @char_is_control(i32)");
    emit_line("declare i32 @char_to_uppercase(i32)");
    emit_line("declare i32 @char_to_lowercase(i32)");
    emit_line("declare i32 @char_to_digit(i32, i32)");
    emit_line("declare i32 @char_from_digit(i32, i32)");
    emit_line("declare i32 @char_code(i32)");
    emit_line("declare i32 @char_from_code(i32)");
    emit_line("declare ptr @char_to_string(i8)");
    emit_line("declare ptr @utf8_2byte_to_string(i8, i8)");
    emit_line("declare ptr @utf8_3byte_to_string(i8, i8, i8)");
    emit_line("declare ptr @utf8_4byte_to_string(i8, i8, i8, i8)");
    emit_line("declare i64 @tml_random_seed()");
    emit_line("");

    // Register random_seed in functions_ map for lowlevel calls
    functions_["random_seed"] = FuncInfo{"@tml_random_seed", "i64 ()", "i64", {}};
    // Also register with tml_ prefix for when called as tml_random_seed()
    functions_["tml_random_seed"] = FuncInfo{"@tml_random_seed", "i64 ()", "i64", {}};

    // Register UTF-8 encoding functions for lowlevel calls
    functions_["char_to_string"] = FuncInfo{"@char_to_string", "ptr (i8)", "ptr", {"i8"}};
    functions_["utf8_2byte_to_string"] =
        FuncInfo{"@utf8_2byte_to_string", "ptr (i8, i8)", "ptr", {"i8", "i8"}};
    functions_["utf8_3byte_to_string"] =
        FuncInfo{"@utf8_3byte_to_string", "ptr (i8, i8, i8)", "ptr", {"i8", "i8", "i8"}};
    functions_["utf8_4byte_to_string"] =
        FuncInfo{"@utf8_4byte_to_string", "ptr (i8, i8, i8, i8)", "ptr", {"i8", "i8", "i8", "i8"}};

    // Register string runtime functions in functions_ map for lowlevel calls from core::str
    functions_["str_len"] = FuncInfo{"@str_len", "i32 (ptr)", "i32", {"ptr"}};
    functions_["str_eq"] = FuncInfo{"@str_eq", "i32 (ptr, ptr)", "i32", {"ptr", "ptr"}};
    functions_["str_hash"] = FuncInfo{"@str_hash", "i32 (ptr)", "i32", {"ptr"}};
    functions_["str_concat"] = FuncInfo{"@str_concat", "ptr (ptr, ptr)", "ptr", {"ptr", "ptr"}};
    functions_["str_concat_opt"] =
        FuncInfo{"@str_concat_opt", "ptr (ptr, ptr)", "ptr", {"ptr", "ptr"}};
    functions_["str_concat_3"] =
        FuncInfo{"@str_concat_3", "ptr (ptr, ptr, ptr)", "ptr", {"ptr", "ptr", "ptr"}};
    functions_["str_concat_4"] =
        FuncInfo{"@str_concat_4", "ptr (ptr, ptr, ptr, ptr)", "ptr", {"ptr", "ptr", "ptr", "ptr"}};
    functions_["str_substring"] =
        FuncInfo{"@str_substring", "ptr (ptr, i32, i32)", "ptr", {"ptr", "i32", "i32"}};
    functions_["str_slice"] =
        FuncInfo{"@str_slice", "ptr (ptr, i64, i64)", "ptr", {"ptr", "i64", "i64"}};
    functions_["str_contains"] = FuncInfo{"@str_contains", "i32 (ptr, ptr)", "i32", {"ptr", "ptr"}};
    functions_["str_starts_with"] =
        FuncInfo{"@str_starts_with", "i32 (ptr, ptr)", "i32", {"ptr", "ptr"}};
    functions_["str_ends_with"] =
        FuncInfo{"@str_ends_with", "i32 (ptr, ptr)", "i32", {"ptr", "ptr"}};
    functions_["str_to_upper"] = FuncInfo{"@str_to_upper", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["str_to_lower"] = FuncInfo{"@str_to_lower", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["str_trim"] = FuncInfo{"@str_trim", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["str_trim_start"] = FuncInfo{"@str_trim_start", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["str_trim_end"] = FuncInfo{"@str_trim_end", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["str_char_at"] = FuncInfo{"@str_char_at", "i32 (ptr, i32)", "i32", {"ptr", "i32"}};
    functions_["str_find"] = FuncInfo{"@str_find", "i64 (ptr, ptr)", "i64", {"ptr", "ptr"}};
    functions_["str_rfind"] = FuncInfo{"@str_rfind", "i64 (ptr, ptr)", "i64", {"ptr", "ptr"}};
    functions_["str_parse_i64"] = FuncInfo{"@str_parse_i64", "i64 (ptr)", "i64", {"ptr"}};
    functions_["str_replace"] =
        FuncInfo{"@str_replace", "ptr (ptr, ptr, ptr)", "ptr", {"ptr", "ptr", "ptr"}};
    functions_["str_split"] = FuncInfo{"@str_split", "ptr (ptr, ptr)", "ptr", {"ptr", "ptr"}};
    functions_["str_split_whitespace"] =
        FuncInfo{"@str_split_whitespace", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["str_lines"] = FuncInfo{"@str_lines", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["str_chars"] = FuncInfo{"@str_chars", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["str_replace_first"] =
        FuncInfo{"@str_replace_first", "ptr (ptr, ptr, ptr)", "ptr", {"ptr", "ptr", "ptr"}};
    functions_["str_repeat"] = FuncInfo{"@str_repeat", "ptr (ptr, i32)", "ptr", {"ptr", "i32"}};
    functions_["str_parse_i32"] = FuncInfo{"@str_parse_i32", "i32 (ptr)", "i32", {"ptr"}};
    functions_["str_parse_f64"] = FuncInfo{"@str_parse_f64", "double (ptr)", "double", {"ptr"}};
    functions_["str_join"] = FuncInfo{"@str_join", "ptr (ptr, ptr)", "ptr", {"ptr", "ptr"}};
    functions_["str_as_bytes"] = FuncInfo{"@str_as_bytes", "ptr (ptr)", "ptr", {"ptr"}};
    // Also register names used in lowlevel blocks that differ from runtime names
    functions_["str_to_uppercase"] = FuncInfo{"@str_to_upper", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["str_to_lowercase"] = FuncInfo{"@str_to_lower", "ptr (ptr)", "ptr", {"ptr"}};

    // Register float formatting runtime functions for lowlevel calls from core::fmt::float
    functions_["f64_to_string"] = FuncInfo{"@f64_to_string", "ptr (double)", "ptr", {"double"}};
    functions_["f32_to_string"] = FuncInfo{"@f32_to_string", "ptr (float)", "ptr", {"float"}};
    functions_["f64_to_string_precision"] =
        FuncInfo{"@f64_to_string_precision", "ptr (double, i64)", "ptr", {"double", "i64"}};
    functions_["f32_to_string_precision"] =
        FuncInfo{"@f32_to_string_precision", "ptr (float, i64)", "ptr", {"float", "i64"}};
    functions_["f64_to_exp_string"] =
        FuncInfo{"@f64_to_exp_string", "ptr (double, i32)", "ptr", {"double", "i32"}};
    functions_["f32_to_exp_string"] =
        FuncInfo{"@f32_to_exp_string", "ptr (float, i32)", "ptr", {"float", "i32"}};
    functions_["f64_is_nan"] = FuncInfo{"@f64_is_nan", "i32 (double)", "i32", {"double"}};
    functions_["f64_is_infinite"] = FuncInfo{"@f64_is_infinite", "i32 (double)", "i32", {"double"}};
    functions_["f32_is_nan"] = FuncInfo{"@f32_is_nan", "i32 (float)", "i32", {"float"}};
    functions_["f32_is_infinite"] = FuncInfo{"@f32_is_infinite", "i32 (float)", "i32", {"float"}};

    // StringBuilder utilities (matches runtime/string.c)
    emit_line("; StringBuilder utilities");
    emit_line("declare ptr @strbuilder_create(i64)");
    emit_line("declare void @strbuilder_destroy(ptr)");
    emit_line("declare void @strbuilder_push(ptr, i32)");
    emit_line("declare void @strbuilder_push_str(ptr, ptr)");
    emit_line("declare i64 @strbuilder_len(ptr)");
    emit_line("declare i64 @strbuilder_capacity(ptr)");
    emit_line("declare void @strbuilder_clear(ptr)");
    emit_line("declare ptr @strbuilder_to_str(ptr)");
    emit_line("declare ptr @strbuilder_as_str(ptr)");
    emit_line("");

    // Text type runtime (matches runtime/text.c)
    emit_line("; Text type runtime (dynamic strings with SSO)");
    emit_line("declare ptr @tml_text_new()");
    emit_line("declare ptr @tml_text_from_str(ptr)");
    emit_line("declare ptr @tml_text_with_capacity(i64)");
    emit_line("declare ptr @tml_text_clone(ptr)");
    emit_line("declare void @tml_text_drop(ptr)");
    emit_line("declare i64 @tml_text_len(ptr)");
    emit_line("declare i64 @tml_text_capacity(ptr)");
    emit_line("declare i32 @tml_text_is_empty(ptr)");
    emit_line("declare ptr @tml_text_data(ptr)");
    emit_line("declare i32 @tml_text_byte_at(ptr, i64)");
    emit_line("declare void @tml_text_clear(ptr)");
    emit_line("declare ptr @tml_text_data_ptr(ptr)");
    emit_line("declare void @tml_text_set_len(ptr, i64)");
    emit_line("declare void @tml_text_push(ptr, i32)");
    emit_line("declare void @tml_text_push_str(ptr, ptr)");
    emit_line("declare void @tml_text_push_str_len(ptr, ptr, i64)");
    emit_line("declare void @tml_text_push_i64(ptr, i64)");
    emit_line("declare i64 @tml_text_push_i64_unsafe(ptr, i64)");
    emit_line("declare void @tml_text_push_formatted(ptr, ptr, i64, i64, ptr, i64)");
    emit_line("declare void @tml_text_push_log(ptr, ptr, i64, i64, ptr, i64, i64, ptr, i64, i64, "
              "ptr, i64)");
    emit_line("declare void @tml_text_reserve(ptr, i64)");
    emit_line("declare void @tml_text_fill_char(ptr, i32, i64)");
    emit_line("declare void @tml_text_push_path(ptr, ptr, i64, i64, ptr, i64, i64, ptr, i64)");
    emit_line("declare i64 @tml_text_index_of(ptr, ptr)");
    emit_line("declare i64 @tml_text_last_index_of(ptr, ptr)");
    emit_line("declare i32 @tml_text_starts_with(ptr, ptr)");
    emit_line("declare i32 @tml_text_ends_with(ptr, ptr)");
    emit_line("declare i32 @tml_text_contains(ptr, ptr)");
    emit_line("declare ptr @tml_text_to_upper(ptr)");
    emit_line("declare ptr @tml_text_to_lower(ptr)");
    emit_line("declare ptr @tml_text_trim(ptr)");
    emit_line("declare ptr @tml_text_trim_start(ptr)");
    emit_line("declare ptr @tml_text_trim_end(ptr)");
    emit_line("declare ptr @tml_text_substring(ptr, i64, i64)");
    emit_line("declare ptr @tml_text_repeat(ptr, i64)");
    emit_line("declare ptr @tml_text_replace(ptr, ptr, ptr)");
    emit_line("declare ptr @tml_text_replace_all(ptr, ptr, ptr)");
    emit_line("declare ptr @tml_text_reverse(ptr)");
    emit_line("declare ptr @tml_text_pad_start(ptr, i64, i32)");
    emit_line("declare ptr @tml_text_pad_end(ptr, i64, i32)");
    emit_line("declare i32 @tml_text_compare(ptr, ptr)");
    emit_line("declare i32 @tml_text_equals(ptr, ptr)");
    emit_line("declare ptr @tml_text_concat(ptr, ptr)");
    emit_line("declare ptr @tml_text_concat_str(ptr, ptr)");
    emit_line("declare ptr @tml_text_as_cstr(ptr)");
    emit_line("declare ptr @tml_text_from_i64(i64)");
    emit_line("declare ptr @tml_text_from_u64(i64)");
    emit_line("declare ptr @tml_text_from_f64(double, i32)");
    emit_line("declare ptr @tml_text_from_bool(i32)");
    emit_line("declare void @tml_text_print(ptr)");
    emit_line("declare void @tml_text_println(ptr)");
    emit_line("");

    // Register text runtime functions in functions_ map for lowlevel calls
    // Key is function name without tml_ prefix (used in lowlevel blocks)
    functions_["text_new"] = FuncInfo{"@tml_text_new", "ptr ()", "ptr", {}};
    functions_["text_from_str"] = FuncInfo{"@tml_text_from_str", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["text_with_capacity"] =
        FuncInfo{"@tml_text_with_capacity", "ptr (i64)", "ptr", {"i64"}};
    functions_["text_clone"] = FuncInfo{"@tml_text_clone", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["text_drop"] = FuncInfo{"@tml_text_drop", "void (ptr)", "void", {"ptr"}};
    functions_["text_len"] = FuncInfo{"@tml_text_len", "i64 (ptr)", "i64", {"ptr"}};
    functions_["text_capacity"] = FuncInfo{"@tml_text_capacity", "i64 (ptr)", "i64", {"ptr"}};
    functions_["text_is_empty"] = FuncInfo{"@tml_text_is_empty", "i32 (ptr)", "i32", {"ptr"}};
    functions_["text_data"] = FuncInfo{"@tml_text_data", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["text_byte_at"] =
        FuncInfo{"@tml_text_byte_at", "i32 (ptr, i64)", "i32", {"ptr", "i64"}};
    functions_["text_clear"] = FuncInfo{"@tml_text_clear", "void (ptr)", "void", {"ptr"}};
    functions_["text_data_ptr"] = FuncInfo{"@tml_text_data_ptr", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["text_set_len"] =
        FuncInfo{"@tml_text_set_len", "void (ptr, i64)", "void", {"ptr", "i64"}};
    functions_["text_push"] = FuncInfo{"@tml_text_push", "void (ptr, i32)", "void", {"ptr", "i32"}};
    functions_["text_push_str"] =
        FuncInfo{"@tml_text_push_str", "void (ptr, ptr)", "void", {"ptr", "ptr"}};
    functions_["text_push_str_len"] =
        FuncInfo{"@tml_text_push_str_len", "void (ptr, ptr, i64)", "void", {"ptr", "ptr", "i64"}};
    functions_["text_push_i64"] =
        FuncInfo{"@tml_text_push_i64", "void (ptr, i64)", "void", {"ptr", "i64"}};
    functions_["text_push_formatted"] = FuncInfo{"@tml_text_push_formatted",
                                                 "void (ptr, ptr, i64, i64, ptr, i64)",
                                                 "void",
                                                 {"ptr", "ptr", "i64", "i64", "ptr", "i64"}};
    functions_["text_push_log"] = FuncInfo{
        "@tml_text_push_log",
        "void (ptr, ptr, i64, i64, ptr, i64, i64, ptr, i64, i64, ptr, i64)",
        "void",
        {"ptr", "ptr", "i64", "i64", "ptr", "i64", "i64", "ptr", "i64", "i64", "ptr", "i64"}};
    functions_["text_reserve"] =
        FuncInfo{"@tml_text_reserve", "void (ptr, i64)", "void", {"ptr", "i64"}};
    functions_["text_fill_char"] =
        FuncInfo{"@tml_text_fill_char", "void (ptr, i32, i64)", "void", {"ptr", "i32", "i64"}};
    functions_["text_push_path"] =
        FuncInfo{"@tml_text_push_path",
                 "void (ptr, ptr, i64, i64, ptr, i64, i64, ptr, i64)",
                 "void",
                 {"ptr", "ptr", "i64", "i64", "ptr", "i64", "i64", "ptr", "i64"}};
    functions_["text_index_of"] =
        FuncInfo{"@tml_text_index_of", "i64 (ptr, ptr)", "i64", {"ptr", "ptr"}};
    functions_["text_last_index_of"] =
        FuncInfo{"@tml_text_last_index_of", "i64 (ptr, ptr)", "i64", {"ptr", "ptr"}};
    functions_["text_starts_with"] =
        FuncInfo{"@tml_text_starts_with", "i32 (ptr, ptr)", "i32", {"ptr", "ptr"}};
    functions_["text_ends_with"] =
        FuncInfo{"@tml_text_ends_with", "i32 (ptr, ptr)", "i32", {"ptr", "ptr"}};
    functions_["text_contains"] =
        FuncInfo{"@tml_text_contains", "i32 (ptr, ptr)", "i32", {"ptr", "ptr"}};
    functions_["text_to_upper"] = FuncInfo{"@tml_text_to_upper", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["text_to_lower"] = FuncInfo{"@tml_text_to_lower", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["text_trim"] = FuncInfo{"@tml_text_trim", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["text_trim_start"] = FuncInfo{"@tml_text_trim_start", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["text_trim_end"] = FuncInfo{"@tml_text_trim_end", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["text_substring"] =
        FuncInfo{"@tml_text_substring", "ptr (ptr, i64, i64)", "ptr", {"ptr", "i64", "i64"}};
    functions_["text_repeat"] =
        FuncInfo{"@tml_text_repeat", "ptr (ptr, i64)", "ptr", {"ptr", "i64"}};
    functions_["text_replace"] =
        FuncInfo{"@tml_text_replace", "ptr (ptr, ptr, ptr)", "ptr", {"ptr", "ptr", "ptr"}};
    functions_["text_replace_all"] =
        FuncInfo{"@tml_text_replace_all", "ptr (ptr, ptr, ptr)", "ptr", {"ptr", "ptr", "ptr"}};
    functions_["text_reverse"] = FuncInfo{"@tml_text_reverse", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["text_pad_start"] =
        FuncInfo{"@tml_text_pad_start", "ptr (ptr, i64, i32)", "ptr", {"ptr", "i64", "i32"}};
    functions_["text_pad_end"] =
        FuncInfo{"@tml_text_pad_end", "ptr (ptr, i64, i32)", "ptr", {"ptr", "i64", "i32"}};
    functions_["text_compare"] =
        FuncInfo{"@tml_text_compare", "i32 (ptr, ptr)", "i32", {"ptr", "ptr"}};
    functions_["text_equals"] =
        FuncInfo{"@tml_text_equals", "i32 (ptr, ptr)", "i32", {"ptr", "ptr"}};
    functions_["text_concat"] =
        FuncInfo{"@tml_text_concat", "ptr (ptr, ptr)", "ptr", {"ptr", "ptr"}};
    functions_["text_concat_str"] =
        FuncInfo{"@tml_text_concat_str", "ptr (ptr, ptr)", "ptr", {"ptr", "ptr"}};
    functions_["text_as_cstr"] = FuncInfo{"@tml_text_as_cstr", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["text_from_i64"] = FuncInfo{"@tml_text_from_i64", "ptr (i64)", "ptr", {"i64"}};
    functions_["text_from_u64"] = FuncInfo{"@tml_text_from_u64", "ptr (i64)", "ptr", {"i64"}};
    functions_["text_from_f64"] =
        FuncInfo{"@tml_text_from_f64", "ptr (double, i32)", "ptr", {"double", "i32"}};
    functions_["text_from_bool"] = FuncInfo{"@tml_text_from_bool", "ptr (i32)", "ptr", {"i32"}};
    functions_["text_print"] = FuncInfo{"@tml_text_print", "void (ptr)", "void", {"ptr"}};
    functions_["text_println"] = FuncInfo{"@tml_text_println", "void (ptr)", "void", {"ptr"}};

    // Time functions (matches runtime/time.c)
    emit_line("; Time functions");
    emit_line("declare i32 @time_ms()");
    emit_line("declare i64 @time_us()");
    emit_line("declare i64 @time_ns()");
    emit_line("declare void @sleep_ms(i32)");
    emit_line("declare void @sleep_us(i64)");
    emit_line("declare i32 @elapsed_ms(i32)");
    emit_line("declare i64 @elapsed_us(i64)");
    emit_line("declare i64 @elapsed_ns(i64)");
    emit_line("declare i64 @instant_now()");
    emit_line("declare i64 @instant_elapsed(i64)");
    emit_line("");

    // Memory functions (matches runtime/mem.c)
    emit_line("; Memory functions");
    emit_line("declare ptr @mem_alloc(i64)");
    emit_line("declare ptr @mem_alloc_zeroed(i64)");
    emit_line("declare ptr @mem_realloc(ptr, i64)");
    emit_line("declare void @mem_free(ptr)");
    emit_line("declare void @mem_copy(ptr, ptr, i64)");
    emit_line("declare void @mem_move(ptr, ptr, i64)");
    emit_line("declare void @mem_set(ptr, i32, i64)");
    emit_line("declare void @mem_zero(ptr, i64)");
    emit_line("declare i32 @mem_compare(ptr, ptr, i64)");
    emit_line("declare i32 @mem_eq(ptr, ptr, i64)");
    emit_line("");

    // Object pool functions (for @pool classes)
    emit_line("; Object pool functions");
    emit_line("declare ptr @pool_acquire(ptr, i64)");
    emit_line("declare void @pool_release(ptr, ptr)");
    emit_line("declare void @pool_init(ptr, i64, i64)");
    emit_line("declare void @pool_destroy(ptr)");
    emit_line("declare i64 @pool_count(ptr)");
    emit_line("declare i64 @pool_capacity(ptr)");
    emit_line("");

    // Thread-local pool functions (for @pool(thread_local: true) classes)
    emit_line("; Thread-local pool functions");
    emit_line("declare ptr @tls_pool_acquire(ptr, i64)");
    emit_line("declare void @tls_pool_release(ptr, ptr, i64)");
    emit_line("declare void @tls_pools_cleanup()");
    emit_line("declare i32 @tls_pool_stats(ptr, ptr, ptr)");
    emit_line("");

    // Network socket functions (matches runtime/net.c)
    // Track in declared_externals_ to prevent duplicate declarations from lowlevel funcs
    emit_line("; Network socket functions");
    emit_line("declare i64 @sys_socket_raw(i32, i32, i32)");
    declared_externals_.insert("sys_socket_raw");
    emit_line("declare i32 @sys_bind_v4(i64, i32, i16)");
    declared_externals_.insert("sys_bind_v4");
    emit_line("declare i32 @sys_bind_v6(i64, ptr, i16, i32, i32)");
    declared_externals_.insert("sys_bind_v6");
    emit_line("declare i32 @sys_listen_raw(i64, i32)");
    declared_externals_.insert("sys_listen_raw");
    emit_line("declare i64 @sys_accept_v4(i64, ptr, ptr)");
    declared_externals_.insert("sys_accept_v4");
    emit_line("declare i32 @sys_connect_v4(i64, i32, i16)");
    declared_externals_.insert("sys_connect_v4");
    emit_line("declare i32 @sys_connect_v6(i64, ptr, i16, i32, i32)");
    declared_externals_.insert("sys_connect_v6");
    emit_line("declare i64 @sys_send_raw(i64, ptr, i64, i32)");
    declared_externals_.insert("sys_send_raw");
    emit_line("declare i64 @sys_recv_raw(i64, ptr, i64, i32)");
    declared_externals_.insert("sys_recv_raw");
    emit_line("declare i64 @sys_sendto_v4(i64, ptr, i64, i32, i32, i16)");
    declared_externals_.insert("sys_sendto_v4");
    emit_line("declare i64 @sys_recvfrom_v4(i64, ptr, i64, i32, ptr, ptr)");
    declared_externals_.insert("sys_recvfrom_v4");
    emit_line("declare i32 @sys_shutdown_raw(i64, i32)");
    declared_externals_.insert("sys_shutdown_raw");
    emit_line("declare i32 @sys_close_raw(i64)");
    declared_externals_.insert("sys_close_raw");
    emit_line("declare i32 @sys_set_nonblocking_raw(i64, i32)");
    declared_externals_.insert("sys_set_nonblocking_raw");
    emit_line("declare i32 @sys_setsockopt_raw(i64, i32, i32, i32)");
    declared_externals_.insert("sys_setsockopt_raw");
    emit_line("declare i32 @sys_getsockname_v4(i64, ptr, ptr)");
    declared_externals_.insert("sys_getsockname_v4");
    emit_line("declare i32 @sys_getpeername_v4(i64, ptr, ptr)");
    declared_externals_.insert("sys_getpeername_v4");
    emit_line("declare i32 @sys_get_last_error()");
    declared_externals_.insert("sys_get_last_error");
    emit_line("declare i32 @sys_wsa_startup()");
    declared_externals_.insert("sys_wsa_startup");
    emit_line("declare void @sys_wsa_cleanup()");
    declared_externals_.insert("sys_wsa_cleanup");
    emit_line("");

    // TLS/SSL functions (matches runtime/net/tls.c)
    emit_line("; TLS/SSL functions");
    emit_line("declare void @tls_init()");
    declared_externals_.insert("tls_init");
    emit_line("declare ptr @tls_context_client_new()");
    declared_externals_.insert("tls_context_client_new");
    emit_line("declare ptr @tls_context_server_new()");
    declared_externals_.insert("tls_context_server_new");
    emit_line("declare void @tls_context_free(ptr)");
    declared_externals_.insert("tls_context_free");
    emit_line("declare i32 @tls_context_set_certificate(ptr, ptr)");
    declared_externals_.insert("tls_context_set_certificate");
    emit_line("declare i32 @tls_context_set_private_key(ptr, ptr)");
    declared_externals_.insert("tls_context_set_private_key");
    emit_line("declare i32 @tls_context_set_ca(ptr, ptr, ptr)");
    declared_externals_.insert("tls_context_set_ca");
    emit_line("declare void @tls_context_set_verify_mode(ptr, i32)");
    declared_externals_.insert("tls_context_set_verify_mode");
    emit_line("declare i32 @tls_context_set_min_version(ptr, i32)");
    declared_externals_.insert("tls_context_set_min_version");
    emit_line("declare i32 @tls_context_set_max_version(ptr, i32)");
    declared_externals_.insert("tls_context_set_max_version");
    emit_line("declare i32 @tls_context_set_alpn(ptr, ptr, i32)");
    declared_externals_.insert("tls_context_set_alpn");
    emit_line("declare i32 @tls_context_set_ciphers(ptr, ptr)");
    declared_externals_.insert("tls_context_set_ciphers");
    emit_line("declare i32 @tls_context_set_ciphersuites(ptr, ptr)");
    declared_externals_.insert("tls_context_set_ciphersuites");
    emit_line("declare ptr @tls_stream_new(ptr, i64)");
    declared_externals_.insert("tls_stream_new");
    emit_line("declare i32 @tls_stream_set_hostname(ptr, ptr)");
    declared_externals_.insert("tls_stream_set_hostname");
    emit_line("declare i32 @tls_stream_connect(ptr)");
    declared_externals_.insert("tls_stream_connect");
    emit_line("declare i32 @tls_stream_accept(ptr)");
    declared_externals_.insert("tls_stream_accept");
    emit_line("declare i64 @tls_stream_read(ptr, ptr, i64)");
    declared_externals_.insert("tls_stream_read");
    emit_line("declare i64 @tls_stream_write(ptr, ptr, i64)");
    declared_externals_.insert("tls_stream_write");
    emit_line("declare i32 @tls_stream_shutdown(ptr)");
    declared_externals_.insert("tls_stream_shutdown");
    emit_line("declare void @tls_stream_free(ptr)");
    declared_externals_.insert("tls_stream_free");
    emit_line("declare ptr @tls_stream_get_version(ptr)");
    declared_externals_.insert("tls_stream_get_version");
    emit_line("declare ptr @tls_stream_get_cipher(ptr)");
    declared_externals_.insert("tls_stream_get_cipher");
    emit_line("declare ptr @tls_stream_get_alpn(ptr)");
    declared_externals_.insert("tls_stream_get_alpn");
    emit_line("declare ptr @tls_stream_get_peer_cn(ptr)");
    declared_externals_.insert("tls_stream_get_peer_cn");
    emit_line("declare ptr @tls_stream_get_peer_cert_pem(ptr)");
    declared_externals_.insert("tls_stream_get_peer_cert_pem");
    emit_line("declare i32 @tls_stream_get_verify_result(ptr)");
    declared_externals_.insert("tls_stream_get_verify_result");
    emit_line("declare i32 @tls_stream_peer_verified(ptr)");
    declared_externals_.insert("tls_stream_peer_verified");
    emit_line("declare ptr @tls_get_error()");
    declared_externals_.insert("tls_get_error");
    // Lowlevel wrappers (tml_ prefix for buffer-passing functions)
    emit_line("declare i64 @tml_tls_stream_read(ptr, ptr, i64)");
    declared_externals_.insert("tml_tls_stream_read");
    emit_line("declare i64 @tml_tls_stream_write(ptr, ptr, i64)");
    declared_externals_.insert("tml_tls_stream_write");
    emit_line("declare i64 @tml_tls_stream_write_str(ptr, ptr, i64)");
    declared_externals_.insert("tml_tls_stream_write_str");
    emit_line("");

    // Format strings for print/println
    // Size calculation: count actual bytes (each escape like \0A = 1 byte, not 3)
    emit_line("; Format strings");
    emit_line("@.fmt.int = private constant [4 x i8] c\"%d\\0A\\00\"");        // %d\n\0 = 4 bytes
    emit_line("@.fmt.int.no_nl = private constant [3 x i8] c\"%d\\00\"");      // %d\0 = 3 bytes
    emit_line("@.fmt.i64 = private constant [5 x i8] c\"%ld\\0A\\00\"");       // %ld\n\0 = 5 bytes
    emit_line("@.fmt.i64.no_nl = private constant [4 x i8] c\"%ld\\00\"");     // %ld\0 = 4 bytes
    emit_line("@.fmt.float = private constant [4 x i8] c\"%f\\0A\\00\"");      // %f\n\0 = 4 bytes
    emit_line("@.fmt.float.no_nl = private constant [3 x i8] c\"%f\\00\"");    // %f\0 = 3 bytes
    emit_line("@.fmt.float3 = private constant [6 x i8] c\"%.3f\\0A\\00\"");   // %.3f\n\0 = 6 bytes
    emit_line("@.fmt.float3.no_nl = private constant [5 x i8] c\"%.3f\\00\""); // %.3f\0 = 5 bytes
    emit_line("@.fmt.str.no_nl = private constant [3 x i8] c\"%s\\00\"");      // %s\0 = 3 bytes
    emit_line("@.str.true = private constant [5 x i8] c\"true\\00\"");         // true\0 = 5 bytes
    emit_line("@.str.false = private constant [6 x i8] c\"false\\00\"");       // false\0 = 6 bytes
    emit_line("@.str.space = private constant [2 x i8] c\" \\00\"");           // " "\0 = 2 bytes
    emit_line("@.str.newline = private constant [2 x i8] c\"\\0A\\00\"");      // \n\0 = 2 bytes
    emit_line("");
}

// emit_module_lowlevel_decls, emit_module_pure_tml_functions, and
// emit_string_constants are in runtime_modules.cpp

} // namespace tml::codegen
