//! # LLVM IR Generator - Runtime Declarations
//!
//! This file emits runtime declarations and module imports.
//!
//! ## Emitted Sections
//!
//! | Method                         | Emits                         |
//! |--------------------------------|-------------------------------|
//! | `emit_header`                  | Target triple, comments       |
//! | `emit_runtime_decls`           | Struct types, C functions     |
//! | `emit_module_lowlevel_decls`   | FFI function declarations     |
//! | `emit_module_pure_tml_functions`| Imported TML functions       |
//! | `emit_string_constants`        | Global string literals        |
//!
//! ## Runtime Types
//!
//! | Type            | Layout              | Purpose             |
//! |-----------------|---------------------|---------------------|
//! | `%struct.tml_str` | `{ ptr, i64 }`    | String slice        |
//! | `%struct.File`  | `{ ptr }`           | File handle         |
//! | `%struct.Path`  | `{ ptr }`           | Path string         |
//! | `%struct.Ordering` | `{ i32 }`        | Comparison result   |
//!
//! ## External Functions
//!
//! Declares C standard library functions: printf, puts, malloc, free, exit.

#include "codegen/llvm_ir_gen.hpp"
#include "lexer/lexer.hpp"
#include "lexer/source.hpp"
#include "parser/parser.hpp"

#include <filesystem>
#include <iostream>
#include <unordered_set>

namespace tml::codegen {

// Helper: Get the LLVM type string for a constant's declared type
static std::string get_const_llvm_type(const parser::TypePtr& type) {
    if (!type)
        return "i64"; // Default fallback

    if (type->is<parser::NamedType>()) {
        const auto& named = type->as<parser::NamedType>();
        if (!named.path.segments.empty()) {
            const std::string& name = named.path.segments.back();
            // Map TML primitive types to LLVM types
            if (name == "I8" || name == "U8")
                return "i8";
            if (name == "I16" || name == "U16")
                return "i16";
            if (name == "I32" || name == "U32")
                return "i32";
            if (name == "I64" || name == "U64")
                return "i64";
            if (name == "I128" || name == "U128")
                return "i128";
            if (name == "Bool")
                return "i1";
            if (name == "Isize" || name == "Usize")
                return "i64";
        }
    }
    return "i64"; // Default for unknown types
}

void LLVMIRGen::emit_header() {
    emit_line("; Generated by TML Compiler");
    emit_line("target triple = \"" + options_.target_triple + "\"");
    emit_line("");
}

void LLVMIRGen::emit_runtime_decls() {
    // String type: { ptr, i64 } (pointer to data, length)
    emit_line("; Runtime type declarations");
    emit_line("%struct.tml_str = type { ptr, i64 }");

    // File I/O types (from std::file)
    emit_line("%struct.File = type { ptr }"); // handle field
    emit_line("%struct.Path = type { ptr }"); // path string field

    // Core comparison type (core::cmp)
    // Ordering is a simple enum: Less=0, Equal=1, Greater=2
    emit_line("%struct.Ordering = type { i32 }");

    // HashMapIter type for iterating over HashMap entries
    emit_line("%struct.HashMapIter = type { ptr }");

    // Buffer type (from std::collections)
    emit_line("%struct.Buffer = type { ptr }"); // handle field

    // Register Buffer fields for field access codegen
    struct_types_["Buffer"] = "%struct.Buffer";
    struct_fields_["Buffer"] = {{"handle", 0, "ptr", types::make_ptr(types::make_unit())}};
    emit_line("");

    // External C functions
    emit_line("; External function declarations");
    emit_line("declare i32 @printf(ptr, ...)");
    emit_line("declare i32 @puts(ptr)");
    emit_line("declare i32 @putchar(i32)");
    emit_line("declare ptr @malloc(i64)");
    emit_line("declare void @free(ptr)");
    emit_line("declare void @exit(i32) noreturn");
    emit_line("declare i64 @strlen(ptr)");
    emit_line("");

    // LLVM intrinsics for optimized codegen
    emit_line("; LLVM intrinsics");
    emit_line("declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)");
    emit_line("declare void @llvm.assume(i1) nounwind");
    emit_line("");

    // TML runtime functions
    emit_line("; TML runtime functions");
    emit_line("declare void @panic(ptr) noreturn");
    emit_line("declare void @assert_tml_loc(i32, ptr, ptr, i32) noreturn");
    emit_line("");

    // Panic catching for @should_panic tests
    // Uses a callback approach: pass function pointer to tml_run_should_panic()
    emit_line("; Panic catching (for @should_panic tests)");
    emit_line("declare i32 @tml_run_should_panic(ptr)");
    emit_line("declare ptr @tml_get_panic_message()");
    emit_line("declare i32 @tml_panic_message_contains(ptr)");
    emit_line("");

    // Note: TML test assertions are now provided by the test module's TML code
    // They call panic() internally and don't need external declarations
    emit_line("");

    // TML code coverage functions
    emit_line("; TML code coverage");
    emit_line("declare void @tml_cover_func(ptr)");
    emit_line("declare void @print_coverage_report()");
    emit_line("declare void @write_coverage_json(ptr)");
    emit_line("declare void @write_coverage_html(ptr)");
    emit_line("");

    // Debug intrinsics (for DWARF debug info)
    if (options_.emit_debug_info) {
        emit_line("; Debug intrinsics");
        emit_line("declare void @llvm.dbg.declare(metadata, metadata, metadata) nounwind readnone");
        emit_line("declare void @llvm.dbg.value(metadata, metadata, metadata) nounwind readnone");
        emit_line("");
    }

    // LLVM instrumentation profile intrinsic (for source-based coverage)
    if (options_.llvm_source_coverage) {
        emit_line("; LLVM instrumentation profile intrinsics (source-based coverage)");
        emit_line("declare void @llvm.instrprof.increment(ptr, i64, i32, i32) #1");
        emit_line("");
    }

    // Stack save/restore intrinsics (for loop alloca cleanup)
    emit_line("; Stack management intrinsics");
    emit_line("declare ptr @llvm.stacksave() nounwind");
    emit_line("declare void @llvm.stackrestore(ptr) nounwind");
    emit_line("");

    // Lifetime intrinsics (for stack slot optimization)
    emit_line("; Lifetime intrinsics for stack optimization");
    emit_line("declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture) nounwind");
    emit_line("declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture) nounwind");
    emit_line("");

    // Threading runtime declarations
    emit_line("; Threading runtime (tml_runtime.c)");
    emit_line("declare ptr @thread_spawn(ptr, ptr)");
    emit_line("declare void @thread_join(ptr)");
    emit_line("declare void @thread_yield()");
    emit_line("declare void @thread_sleep(i32)");
    emit_line("declare i32 @thread_id()");
    emit_line("");

    // I/O functions - all check output suppression flag
    emit_line("; I/O functions (check output suppression)");
    emit_line("declare void @print(ptr)");
    emit_line("declare void @println(ptr)");
    emit_line("declare void @print_i32(i32)");
    emit_line("declare void @print_i64(i64)");
    emit_line("declare void @print_f32(float)");
    emit_line("declare void @print_f64(double)");
    emit_line("declare void @print_bool(i32)");
    emit_line("declare void @print_char(i32)");
    emit_line("");

    // NOTE: Math functions moved to core::math module
    // Import with: use core::math

    // NOTE: Assertion functions moved to test module
    // Import with: use test
    emit_line("; Black box (prevent optimization)");
    emit_line("declare i32 @black_box_i32(i32)");
    emit_line("declare i64 @black_box_i64(i64)");
    emit_line("declare double @black_box_f64(double)");
    emit_line("; SIMD operations (auto-vectorized)");
    emit_line("declare i64 @simd_sum_i32(ptr, i64)");
    emit_line("declare i64 @simd_sum_i64(ptr, i64)");
    emit_line("declare double @simd_sum_f64(ptr, i64)");
    emit_line("declare double @simd_dot_f64(ptr, ptr, i64)");
    emit_line("declare void @simd_fill_i32(ptr, i32, i64)");
    emit_line("declare void @simd_add_i32(ptr, ptr, ptr, i64)");
    emit_line("declare void @simd_mul_i32(ptr, ptr, ptr, i64)");
    emit_line("");

    // Float functions
    emit_line("; Float functions");
    emit_line("declare ptr @float_to_fixed(double, i32)");
    emit_line("declare ptr @float_to_precision(double, i32)");
    emit_line("declare ptr @float_to_string(double)");
    emit_line("declare ptr @f64_to_string(double)"); // F64.to_string() method
    emit_line("declare ptr @f32_to_string(float)");  // F32.to_string() method
    emit_line("declare ptr @float_to_exp(double, i32)");
    emit_line("declare i32 @f64_is_nan(double)");
    emit_line("declare i32 @f64_is_infinite(double)");
    emit_line("declare double @int_to_float(i32)");
    emit_line("declare double @i64_to_float(i64)");
    emit_line("declare i32 @float_to_int(double)");
    emit_line("declare i64 @float_to_i64(double)");
    emit_line("declare i32 @float_round(double)");
    emit_line("declare i32 @float_floor(double)");
    emit_line("declare i32 @float_ceil(double)");
    emit_line("declare double @float_abs(double)");
    emit_line("declare double @float_sqrt(double)");
    emit_line("declare double @float_pow(double, i32)");
    emit_line("");

    // Integer to string conversion
    emit_line("; Integer to string");
    emit_line("declare ptr @i32_to_string(i32)");
    emit_line("declare ptr @i64_to_string(i64)");
    emit_line("declare ptr @bool_to_string(i1)");
    emit_line("");

    // Overloaded abs functions
    emit_line("; Overloaded abs");
    emit_line("declare i32 @abs_i32(i32)");
    emit_line("declare double @abs_f64(double)");
    emit_line("");

    // Bit manipulation runtime declarations
    emit_line("; Bit manipulation runtime");
    emit_line("declare i32 @float32_bits(float)");
    emit_line("declare float @float32_from_bits(i32)");
    emit_line("declare i64 @float64_bits(double)");
    emit_line("declare double @float64_from_bits(i64)");
    emit_line("");

    // Special float value runtime declarations
    emit_line("; Special float values runtime");
    emit_line("declare double @infinity(i32)");
    emit_line("declare double @nan()");
    emit_line("declare i32 @is_inf(double, i32)");
    emit_line("declare i32 @is_nan(double)");
    emit_line("");

    // Nextafter runtime declarations
    emit_line("; Nextafter runtime");
    emit_line("declare double @nextafter(double, double)");
    emit_line("declare float @nextafter32(float, float)");
    emit_line("");

    // Channel runtime declarations
    emit_line("; Channel runtime (Go-style)");
    emit_line("declare ptr @channel_create()");
    emit_line("declare i32 @channel_send(ptr, i32)");
    emit_line("declare i32 @channel_recv(ptr, ptr)");
    emit_line("declare i32 @channel_try_send(ptr, i32)");
    emit_line("declare i32 @channel_try_recv(ptr, ptr)");
    emit_line("declare void @channel_close(ptr)");
    emit_line("declare void @channel_destroy(ptr)");
    emit_line("declare i32 @channel_len(ptr)");
    emit_line("");

    // Mutex runtime declarations
    emit_line("; Mutex runtime");
    emit_line("declare ptr @mutex_create()");
    emit_line("declare void @mutex_lock(ptr)");
    emit_line("declare void @mutex_unlock(ptr)");
    emit_line("declare i32 @mutex_try_lock(ptr)");
    emit_line("declare void @mutex_destroy(ptr)");
    emit_line("");

    // WaitGroup runtime declarations
    emit_line("; WaitGroup runtime (Go-style)");
    emit_line("declare ptr @waitgroup_create()");
    emit_line("declare void @waitgroup_add(ptr, i32)");
    emit_line("declare void @waitgroup_done(ptr)");
    emit_line("declare void @waitgroup_wait(ptr)");
    emit_line("declare void @waitgroup_destroy(ptr)");
    emit_line("");

    // Atomic counter runtime declarations
    emit_line("; Atomic counter runtime");
    emit_line("declare ptr @atomic_counter_create(i32)");
    emit_line("declare i32 @atomic_counter_inc(ptr)");
    emit_line("declare i32 @atomic_counter_dec(ptr)");
    emit_line("declare i32 @atomic_counter_get(ptr)");
    emit_line("declare void @atomic_counter_set(ptr, i32)");
    emit_line("declare void @atomic_counter_destroy(ptr)");
    emit_line("");

    // List runtime declarations
    emit_line("; List (dynamic array) runtime");
    emit_line("declare ptr @list_create(i64)");
    emit_line("declare void @list_destroy(ptr)");
    emit_line("declare void @list_push(ptr, i64)");
    emit_line("declare i64 @list_pop(ptr)");
    emit_line("declare i64 @list_get(ptr, i64)");
    emit_line("declare void @list_set(ptr, i64, i64)");
    emit_line("declare i64 @list_len(ptr)");
    emit_line("declare i64 @list_capacity(ptr)");
    emit_line("declare void @list_clear(ptr)");
    emit_line("declare i32 @list_is_empty(ptr)");
    emit_line("declare void @list_remove(ptr, i64)");
    emit_line("declare i64 @list_first(ptr)");
    emit_line("declare i64 @list_last(ptr)");
    emit_line("");

    // HashMap runtime declarations
    emit_line("; HashMap runtime");
    emit_line("declare ptr @hashmap_create(i64)");
    emit_line("declare void @hashmap_destroy(ptr)");
    emit_line("declare void @hashmap_set(ptr, i64, i64)");
    emit_line("declare i64 @hashmap_get(ptr, i64)");
    emit_line("declare i32 @hashmap_has(ptr, i64)");
    emit_line("declare i32 @hashmap_remove(ptr, i64)");
    emit_line("declare i64 @hashmap_len(ptr)");
    emit_line("declare void @hashmap_clear(ptr)");
    emit_line("declare ptr @hashmap_iter_create(ptr)");
    emit_line("declare void @hashmap_iter_destroy(ptr)");
    emit_line("declare i32 @hashmap_iter_has_next(ptr)");
    emit_line("declare i64 @hashmap_iter_key(ptr)");
    emit_line("declare i64 @hashmap_iter_value(ptr)");
    emit_line("declare void @hashmap_iter_next(ptr)");
    emit_line("");

    // Buffer runtime declarations
    // Register in declared_externals_ to prevent duplicate declarations from @extern modules
    emit_line("; Buffer runtime");
    emit_line("declare ptr @buffer_create(i64)");
    declared_externals_.insert("buffer_create");
    emit_line("declare void @buffer_destroy(ptr)");
    declared_externals_.insert("buffer_destroy");
    emit_line("declare void @buffer_write_byte(ptr, i32)");
    declared_externals_.insert("buffer_write_byte");
    emit_line("declare void @buffer_write_i32(ptr, i32)");
    declared_externals_.insert("buffer_write_i32");
    emit_line("declare void @buffer_write_i64(ptr, i64)");
    declared_externals_.insert("buffer_write_i64");
    emit_line("declare i32 @buffer_read_byte(ptr)");
    declared_externals_.insert("buffer_read_byte");
    emit_line("declare i32 @buffer_read_i32(ptr)");
    declared_externals_.insert("buffer_read_i32");
    emit_line("declare i64 @buffer_read_i64(ptr)");
    declared_externals_.insert("buffer_read_i64");
    emit_line("declare i64 @buffer_len(ptr)");
    declared_externals_.insert("buffer_len");
    emit_line("declare i64 @buffer_capacity(ptr)");
    declared_externals_.insert("buffer_capacity");
    emit_line("declare i64 @buffer_remaining(ptr)");
    declared_externals_.insert("buffer_remaining");
    emit_line("declare void @buffer_clear(ptr)");
    declared_externals_.insert("buffer_clear");
    emit_line("declare void @buffer_reset_read(ptr)");
    declared_externals_.insert("buffer_reset_read");
    emit_line("");

    // File I/O runtime declarations
    emit_line("; File I/O runtime");
    emit_line("declare ptr @file_open_read(ptr)");
    emit_line("declare ptr @file_open_write(ptr)");
    emit_line("declare ptr @file_open_append(ptr)");
    emit_line("declare void @file_close(ptr)");
    emit_line("declare i1 @file_is_open(ptr)");
    emit_line("declare ptr @file_read_line(ptr)");
    emit_line("declare i1 @file_write_str(ptr, ptr)");
    emit_line("declare i64 @file_size(ptr)");
    emit_line("declare ptr @file_read_all(ptr)");
    emit_line("declare i1 @file_write_all(ptr, ptr)");
    emit_line("declare i1 @file_append_all(ptr, ptr)");
    emit_line("");

    // Path utilities runtime declarations
    emit_line("; Path utilities runtime");
    emit_line("declare i1 @path_exists(ptr)");
    emit_line("declare i1 @path_is_file(ptr)");
    emit_line("declare i1 @path_is_dir(ptr)");
    emit_line("declare i1 @path_create_dir(ptr)");
    emit_line("declare i1 @path_create_dir_all(ptr)");
    emit_line("declare i1 @path_remove(ptr)");
    emit_line("declare i1 @path_remove_dir(ptr)");
    emit_line("declare i1 @path_rename(ptr, ptr)");
    emit_line("declare i1 @path_copy(ptr, ptr)");
    emit_line("declare ptr @path_join(ptr, ptr)");
    emit_line("declare ptr @path_parent(ptr)");
    emit_line("declare ptr @path_filename(ptr)");
    emit_line("declare ptr @path_extension(ptr)");
    emit_line("declare ptr @path_absolute(ptr)");
    emit_line("");

    // String utilities (matches runtime/string.c)
    emit_line("; String utilities");
    emit_line("declare i32 @str_len(ptr)");
    emit_line("declare i32 @str_eq(ptr, ptr)");
    emit_line("declare i32 @str_hash(ptr)");
    emit_line("declare ptr @str_concat(ptr, ptr)");
    emit_line("declare ptr @str_concat_opt(ptr, ptr)");         // O(1) amortized
    emit_line("declare ptr @str_concat_3(ptr, ptr, ptr)");      // Fused 3-string concat
    emit_line("declare ptr @str_concat_4(ptr, ptr, ptr, ptr)"); // Fused 4-string concat
    emit_line("declare ptr @str_substring(ptr, i32, i32)");
    emit_line("declare ptr @str_slice(ptr, i64, i64)");
    emit_line("declare i32 @str_contains(ptr, ptr)");
    emit_line("declare i32 @str_starts_with(ptr, ptr)");
    emit_line("declare i32 @str_ends_with(ptr, ptr)");
    emit_line("declare ptr @str_to_upper(ptr)");
    emit_line("declare ptr @str_to_lower(ptr)");
    emit_line("declare ptr @str_trim(ptr)");
    emit_line("declare ptr @str_trim_start(ptr)");
    emit_line("declare ptr @str_trim_end(ptr)");
    emit_line("declare i32 @str_char_at(ptr, i32)");
    emit_line("declare i64 @str_find(ptr, ptr)");
    emit_line("declare i64 @str_rfind(ptr, ptr)");
    emit_line("declare i64 @str_parse_i64(ptr)");
    emit_line("declare ptr @str_replace(ptr, ptr, ptr)");
    emit_line("declare ptr @str_split(ptr, ptr)");
    emit_line("declare ptr @str_chars(ptr)");
    emit_line("declare ptr @i64_to_str(i64)");
    emit_line("declare ptr @f64_to_str(double)");
    emit_line("");

    // Char utilities (matches runtime/string.c)
    emit_line("; Char utilities");
    emit_line("declare i32 @char_is_alphabetic(i32)");
    emit_line("declare i32 @char_is_numeric(i32)");
    emit_line("declare i32 @char_is_alphanumeric(i32)");
    emit_line("declare i32 @char_is_whitespace(i32)");
    emit_line("declare i32 @char_is_uppercase(i32)");
    emit_line("declare i32 @char_is_lowercase(i32)");
    emit_line("declare i32 @char_is_ascii(i32)");
    emit_line("declare i32 @char_is_control(i32)");
    emit_line("declare i32 @char_to_uppercase(i32)");
    emit_line("declare i32 @char_to_lowercase(i32)");
    emit_line("declare i32 @char_to_digit(i32, i32)");
    emit_line("declare i32 @char_from_digit(i32, i32)");
    emit_line("declare i32 @char_code(i32)");
    emit_line("declare i32 @char_from_code(i32)");
    emit_line("declare ptr @char_to_string(i8)");
    emit_line("declare ptr @utf8_2byte_to_string(i8, i8)");
    emit_line("declare ptr @utf8_3byte_to_string(i8, i8, i8)");
    emit_line("declare ptr @utf8_4byte_to_string(i8, i8, i8, i8)");
    emit_line("declare i64 @tml_random_seed()");
    emit_line("");

    // Register random_seed in functions_ map for lowlevel calls
    functions_["random_seed"] = FuncInfo{"@tml_random_seed", "i64 ()", "i64", {}};
    // Also register with tml_ prefix for when called as tml_random_seed()
    functions_["tml_random_seed"] = FuncInfo{"@tml_random_seed", "i64 ()", "i64", {}};

    // Register UTF-8 encoding functions for lowlevel calls
    functions_["char_to_string"] = FuncInfo{"@char_to_string", "ptr (i8)", "ptr", {"i8"}};
    functions_["utf8_2byte_to_string"] =
        FuncInfo{"@utf8_2byte_to_string", "ptr (i8, i8)", "ptr", {"i8", "i8"}};
    functions_["utf8_3byte_to_string"] =
        FuncInfo{"@utf8_3byte_to_string", "ptr (i8, i8, i8)", "ptr", {"i8", "i8", "i8"}};
    functions_["utf8_4byte_to_string"] =
        FuncInfo{"@utf8_4byte_to_string", "ptr (i8, i8, i8, i8)", "ptr", {"i8", "i8", "i8", "i8"}};

    // StringBuilder utilities (matches runtime/string.c)
    emit_line("; StringBuilder utilities");
    emit_line("declare ptr @strbuilder_create(i64)");
    emit_line("declare void @strbuilder_destroy(ptr)");
    emit_line("declare void @strbuilder_push(ptr, i32)");
    emit_line("declare void @strbuilder_push_str(ptr, ptr)");
    emit_line("declare i64 @strbuilder_len(ptr)");
    emit_line("declare i64 @strbuilder_capacity(ptr)");
    emit_line("declare void @strbuilder_clear(ptr)");
    emit_line("declare ptr @strbuilder_to_str(ptr)");
    emit_line("declare ptr @strbuilder_as_str(ptr)");
    emit_line("");

    // Text type runtime (matches runtime/text.c)
    emit_line("; Text type runtime (dynamic strings with SSO)");
    emit_line("declare ptr @tml_text_new()");
    emit_line("declare ptr @tml_text_from_str(ptr)");
    emit_line("declare ptr @tml_text_with_capacity(i64)");
    emit_line("declare ptr @tml_text_clone(ptr)");
    emit_line("declare void @tml_text_drop(ptr)");
    emit_line("declare i64 @tml_text_len(ptr)");
    emit_line("declare i64 @tml_text_capacity(ptr)");
    emit_line("declare i32 @tml_text_is_empty(ptr)");
    emit_line("declare ptr @tml_text_data(ptr)");
    emit_line("declare i32 @tml_text_byte_at(ptr, i64)");
    emit_line("declare void @tml_text_clear(ptr)");
    emit_line("declare ptr @tml_text_data_ptr(ptr)");
    emit_line("declare void @tml_text_set_len(ptr, i64)");
    emit_line("declare void @tml_text_push(ptr, i32)");
    emit_line("declare void @tml_text_push_str(ptr, ptr)");
    emit_line("declare void @tml_text_push_str_len(ptr, ptr, i64)");
    emit_line("declare void @tml_text_push_i64(ptr, i64)");
    emit_line("declare i64 @tml_text_push_i64_unsafe(ptr, i64)");
    emit_line("declare void @tml_text_push_formatted(ptr, ptr, i64, i64, ptr, i64)");
    emit_line("declare void @tml_text_push_log(ptr, ptr, i64, i64, ptr, i64, i64, ptr, i64, i64, "
              "ptr, i64)");
    emit_line("declare void @tml_text_reserve(ptr, i64)");
    emit_line("declare void @tml_text_fill_char(ptr, i32, i64)");
    emit_line("declare void @tml_text_push_path(ptr, ptr, i64, i64, ptr, i64, i64, ptr, i64)");
    emit_line("declare i64 @tml_text_index_of(ptr, ptr)");
    emit_line("declare i64 @tml_text_last_index_of(ptr, ptr)");
    emit_line("declare i32 @tml_text_starts_with(ptr, ptr)");
    emit_line("declare i32 @tml_text_ends_with(ptr, ptr)");
    emit_line("declare i32 @tml_text_contains(ptr, ptr)");
    emit_line("declare ptr @tml_text_to_upper(ptr)");
    emit_line("declare ptr @tml_text_to_lower(ptr)");
    emit_line("declare ptr @tml_text_trim(ptr)");
    emit_line("declare ptr @tml_text_trim_start(ptr)");
    emit_line("declare ptr @tml_text_trim_end(ptr)");
    emit_line("declare ptr @tml_text_substring(ptr, i64, i64)");
    emit_line("declare ptr @tml_text_repeat(ptr, i64)");
    emit_line("declare ptr @tml_text_replace(ptr, ptr, ptr)");
    emit_line("declare ptr @tml_text_replace_all(ptr, ptr, ptr)");
    emit_line("declare ptr @tml_text_reverse(ptr)");
    emit_line("declare ptr @tml_text_pad_start(ptr, i64, i32)");
    emit_line("declare ptr @tml_text_pad_end(ptr, i64, i32)");
    emit_line("declare i32 @tml_text_compare(ptr, ptr)");
    emit_line("declare i32 @tml_text_equals(ptr, ptr)");
    emit_line("declare ptr @tml_text_concat(ptr, ptr)");
    emit_line("declare ptr @tml_text_concat_str(ptr, ptr)");
    emit_line("declare ptr @tml_text_as_cstr(ptr)");
    emit_line("declare ptr @tml_text_from_i64(i64)");
    emit_line("declare ptr @tml_text_from_u64(i64)");
    emit_line("declare ptr @tml_text_from_f64(double, i32)");
    emit_line("declare ptr @tml_text_from_bool(i32)");
    emit_line("declare void @tml_text_print(ptr)");
    emit_line("declare void @tml_text_println(ptr)");
    emit_line("");

    // Register text runtime functions in functions_ map for lowlevel calls
    // Key is function name without tml_ prefix (used in lowlevel blocks)
    functions_["text_new"] = FuncInfo{"@tml_text_new", "ptr ()", "ptr", {}};
    functions_["text_from_str"] = FuncInfo{"@tml_text_from_str", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["text_with_capacity"] =
        FuncInfo{"@tml_text_with_capacity", "ptr (i64)", "ptr", {"i64"}};
    functions_["text_clone"] = FuncInfo{"@tml_text_clone", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["text_drop"] = FuncInfo{"@tml_text_drop", "void (ptr)", "void", {"ptr"}};
    functions_["text_len"] = FuncInfo{"@tml_text_len", "i64 (ptr)", "i64", {"ptr"}};
    functions_["text_capacity"] = FuncInfo{"@tml_text_capacity", "i64 (ptr)", "i64", {"ptr"}};
    functions_["text_is_empty"] = FuncInfo{"@tml_text_is_empty", "i32 (ptr)", "i32", {"ptr"}};
    functions_["text_data"] = FuncInfo{"@tml_text_data", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["text_byte_at"] =
        FuncInfo{"@tml_text_byte_at", "i32 (ptr, i64)", "i32", {"ptr", "i64"}};
    functions_["text_clear"] = FuncInfo{"@tml_text_clear", "void (ptr)", "void", {"ptr"}};
    functions_["text_data_ptr"] = FuncInfo{"@tml_text_data_ptr", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["text_set_len"] =
        FuncInfo{"@tml_text_set_len", "void (ptr, i64)", "void", {"ptr", "i64"}};
    functions_["text_push"] = FuncInfo{"@tml_text_push", "void (ptr, i32)", "void", {"ptr", "i32"}};
    functions_["text_push_str"] =
        FuncInfo{"@tml_text_push_str", "void (ptr, ptr)", "void", {"ptr", "ptr"}};
    functions_["text_push_str_len"] =
        FuncInfo{"@tml_text_push_str_len", "void (ptr, ptr, i64)", "void", {"ptr", "ptr", "i64"}};
    functions_["text_push_i64"] =
        FuncInfo{"@tml_text_push_i64", "void (ptr, i64)", "void", {"ptr", "i64"}};
    functions_["text_push_formatted"] = FuncInfo{"@tml_text_push_formatted",
                                                 "void (ptr, ptr, i64, i64, ptr, i64)",
                                                 "void",
                                                 {"ptr", "ptr", "i64", "i64", "ptr", "i64"}};
    functions_["text_push_log"] = FuncInfo{
        "@tml_text_push_log",
        "void (ptr, ptr, i64, i64, ptr, i64, i64, ptr, i64, i64, ptr, i64)",
        "void",
        {"ptr", "ptr", "i64", "i64", "ptr", "i64", "i64", "ptr", "i64", "i64", "ptr", "i64"}};
    functions_["text_reserve"] =
        FuncInfo{"@tml_text_reserve", "void (ptr, i64)", "void", {"ptr", "i64"}};
    functions_["text_fill_char"] =
        FuncInfo{"@tml_text_fill_char", "void (ptr, i32, i64)", "void", {"ptr", "i32", "i64"}};
    functions_["text_push_path"] =
        FuncInfo{"@tml_text_push_path",
                 "void (ptr, ptr, i64, i64, ptr, i64, i64, ptr, i64)",
                 "void",
                 {"ptr", "ptr", "i64", "i64", "ptr", "i64", "i64", "ptr", "i64"}};
    functions_["text_index_of"] =
        FuncInfo{"@tml_text_index_of", "i64 (ptr, ptr)", "i64", {"ptr", "ptr"}};
    functions_["text_last_index_of"] =
        FuncInfo{"@tml_text_last_index_of", "i64 (ptr, ptr)", "i64", {"ptr", "ptr"}};
    functions_["text_starts_with"] =
        FuncInfo{"@tml_text_starts_with", "i32 (ptr, ptr)", "i32", {"ptr", "ptr"}};
    functions_["text_ends_with"] =
        FuncInfo{"@tml_text_ends_with", "i32 (ptr, ptr)", "i32", {"ptr", "ptr"}};
    functions_["text_contains"] =
        FuncInfo{"@tml_text_contains", "i32 (ptr, ptr)", "i32", {"ptr", "ptr"}};
    functions_["text_to_upper"] = FuncInfo{"@tml_text_to_upper", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["text_to_lower"] = FuncInfo{"@tml_text_to_lower", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["text_trim"] = FuncInfo{"@tml_text_trim", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["text_trim_start"] = FuncInfo{"@tml_text_trim_start", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["text_trim_end"] = FuncInfo{"@tml_text_trim_end", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["text_substring"] =
        FuncInfo{"@tml_text_substring", "ptr (ptr, i64, i64)", "ptr", {"ptr", "i64", "i64"}};
    functions_["text_repeat"] =
        FuncInfo{"@tml_text_repeat", "ptr (ptr, i64)", "ptr", {"ptr", "i64"}};
    functions_["text_replace"] =
        FuncInfo{"@tml_text_replace", "ptr (ptr, ptr, ptr)", "ptr", {"ptr", "ptr", "ptr"}};
    functions_["text_replace_all"] =
        FuncInfo{"@tml_text_replace_all", "ptr (ptr, ptr, ptr)", "ptr", {"ptr", "ptr", "ptr"}};
    functions_["text_reverse"] = FuncInfo{"@tml_text_reverse", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["text_pad_start"] =
        FuncInfo{"@tml_text_pad_start", "ptr (ptr, i64, i32)", "ptr", {"ptr", "i64", "i32"}};
    functions_["text_pad_end"] =
        FuncInfo{"@tml_text_pad_end", "ptr (ptr, i64, i32)", "ptr", {"ptr", "i64", "i32"}};
    functions_["text_compare"] =
        FuncInfo{"@tml_text_compare", "i32 (ptr, ptr)", "i32", {"ptr", "ptr"}};
    functions_["text_equals"] =
        FuncInfo{"@tml_text_equals", "i32 (ptr, ptr)", "i32", {"ptr", "ptr"}};
    functions_["text_concat"] =
        FuncInfo{"@tml_text_concat", "ptr (ptr, ptr)", "ptr", {"ptr", "ptr"}};
    functions_["text_concat_str"] =
        FuncInfo{"@tml_text_concat_str", "ptr (ptr, ptr)", "ptr", {"ptr", "ptr"}};
    functions_["text_as_cstr"] = FuncInfo{"@tml_text_as_cstr", "ptr (ptr)", "ptr", {"ptr"}};
    functions_["text_from_i64"] = FuncInfo{"@tml_text_from_i64", "ptr (i64)", "ptr", {"i64"}};
    functions_["text_from_u64"] = FuncInfo{"@tml_text_from_u64", "ptr (i64)", "ptr", {"i64"}};
    functions_["text_from_f64"] =
        FuncInfo{"@tml_text_from_f64", "ptr (double, i32)", "ptr", {"double", "i32"}};
    functions_["text_from_bool"] = FuncInfo{"@tml_text_from_bool", "ptr (i32)", "ptr", {"i32"}};
    functions_["text_print"] = FuncInfo{"@tml_text_print", "void (ptr)", "void", {"ptr"}};
    functions_["text_println"] = FuncInfo{"@tml_text_println", "void (ptr)", "void", {"ptr"}};

    // Time functions (matches runtime/time.c)
    emit_line("; Time functions");
    emit_line("declare i32 @time_ms()");
    emit_line("declare i64 @time_us()");
    emit_line("declare i64 @time_ns()");
    emit_line("declare void @sleep_ms(i32)");
    emit_line("declare void @sleep_us(i64)");
    emit_line("declare i32 @elapsed_ms(i32)");
    emit_line("declare i64 @elapsed_us(i64)");
    emit_line("declare i64 @elapsed_ns(i64)");
    emit_line("");

    // Memory functions (matches runtime/mem.c)
    emit_line("; Memory functions");
    emit_line("declare ptr @mem_alloc(i64)");
    emit_line("declare ptr @mem_alloc_zeroed(i64)");
    emit_line("declare ptr @mem_realloc(ptr, i64)");
    emit_line("declare void @mem_free(ptr)");
    emit_line("declare void @mem_copy(ptr, ptr, i64)");
    emit_line("declare void @mem_move(ptr, ptr, i64)");
    emit_line("declare void @mem_set(ptr, i32, i64)");
    emit_line("declare void @mem_zero(ptr, i64)");
    emit_line("declare i32 @mem_compare(ptr, ptr, i64)");
    emit_line("declare i32 @mem_eq(ptr, ptr, i64)");
    emit_line("");

    // Object pool functions (for @pool classes)
    emit_line("; Object pool functions");
    emit_line("declare ptr @pool_acquire(ptr, i64)");
    emit_line("declare void @pool_release(ptr, ptr)");
    emit_line("declare void @pool_init(ptr, i64, i64)");
    emit_line("declare void @pool_destroy(ptr)");
    emit_line("declare i64 @pool_count(ptr)");
    emit_line("declare i64 @pool_capacity(ptr)");
    emit_line("");

    // Thread-local pool functions (for @pool(thread_local: true) classes)
    emit_line("; Thread-local pool functions");
    emit_line("declare ptr @tls_pool_acquire(ptr, i64)");
    emit_line("declare void @tls_pool_release(ptr, ptr, i64)");
    emit_line("declare void @tls_pools_cleanup()");
    emit_line("declare i32 @tls_pool_stats(ptr, ptr, ptr)");
    emit_line("");

    // Network socket functions (matches runtime/net.c)
    // Track in declared_externals_ to prevent duplicate declarations from lowlevel funcs
    emit_line("; Network socket functions");
    emit_line("declare i64 @sys_socket_raw(i32, i32, i32)");
    declared_externals_.insert("sys_socket_raw");
    emit_line("declare i32 @sys_bind_v4(i64, i32, i16)");
    declared_externals_.insert("sys_bind_v4");
    emit_line("declare i32 @sys_bind_v6(i64, ptr, i16, i32, i32)");
    declared_externals_.insert("sys_bind_v6");
    emit_line("declare i32 @sys_listen_raw(i64, i32)");
    declared_externals_.insert("sys_listen_raw");
    emit_line("declare i64 @sys_accept_v4(i64, ptr, ptr)");
    declared_externals_.insert("sys_accept_v4");
    emit_line("declare i32 @sys_connect_v4(i64, i32, i16)");
    declared_externals_.insert("sys_connect_v4");
    emit_line("declare i32 @sys_connect_v6(i64, ptr, i16, i32, i32)");
    declared_externals_.insert("sys_connect_v6");
    emit_line("declare i64 @sys_send_raw(i64, ptr, i64, i32)");
    declared_externals_.insert("sys_send_raw");
    emit_line("declare i64 @sys_recv_raw(i64, ptr, i64, i32)");
    declared_externals_.insert("sys_recv_raw");
    emit_line("declare i64 @sys_sendto_v4(i64, ptr, i64, i32, i32, i16)");
    declared_externals_.insert("sys_sendto_v4");
    emit_line("declare i64 @sys_recvfrom_v4(i64, ptr, i64, i32, ptr, ptr)");
    declared_externals_.insert("sys_recvfrom_v4");
    emit_line("declare i32 @sys_shutdown_raw(i64, i32)");
    declared_externals_.insert("sys_shutdown_raw");
    emit_line("declare i32 @sys_close_raw(i64)");
    declared_externals_.insert("sys_close_raw");
    emit_line("declare i32 @sys_set_nonblocking_raw(i64, i32)");
    declared_externals_.insert("sys_set_nonblocking_raw");
    emit_line("declare i32 @sys_setsockopt_raw(i64, i32, i32, i32)");
    declared_externals_.insert("sys_setsockopt_raw");
    emit_line("declare i32 @sys_getsockname_v4(i64, ptr, ptr)");
    declared_externals_.insert("sys_getsockname_v4");
    emit_line("declare i32 @sys_getpeername_v4(i64, ptr, ptr)");
    declared_externals_.insert("sys_getpeername_v4");
    emit_line("declare i32 @sys_get_last_error()");
    declared_externals_.insert("sys_get_last_error");
    emit_line("declare i32 @sys_wsa_startup()");
    declared_externals_.insert("sys_wsa_startup");
    emit_line("declare void @sys_wsa_cleanup()");
    declared_externals_.insert("sys_wsa_cleanup");
    emit_line("");

    // Format strings for print/println
    // Size calculation: count actual bytes (each escape like \0A = 1 byte, not 3)
    emit_line("; Format strings");
    emit_line("@.fmt.int = private constant [4 x i8] c\"%d\\0A\\00\"");        // %d\n\0 = 4 bytes
    emit_line("@.fmt.int.no_nl = private constant [3 x i8] c\"%d\\00\"");      // %d\0 = 3 bytes
    emit_line("@.fmt.i64 = private constant [5 x i8] c\"%ld\\0A\\00\"");       // %ld\n\0 = 5 bytes
    emit_line("@.fmt.i64.no_nl = private constant [4 x i8] c\"%ld\\00\"");     // %ld\0 = 4 bytes
    emit_line("@.fmt.float = private constant [4 x i8] c\"%f\\0A\\00\"");      // %f\n\0 = 4 bytes
    emit_line("@.fmt.float.no_nl = private constant [3 x i8] c\"%f\\00\"");    // %f\0 = 3 bytes
    emit_line("@.fmt.float3 = private constant [6 x i8] c\"%.3f\\0A\\00\"");   // %.3f\n\0 = 6 bytes
    emit_line("@.fmt.float3.no_nl = private constant [5 x i8] c\"%.3f\\00\""); // %.3f\0 = 5 bytes
    emit_line("@.fmt.str.no_nl = private constant [3 x i8] c\"%s\\00\"");      // %s\0 = 3 bytes
    emit_line("@.str.true = private constant [5 x i8] c\"true\\00\"");         // true\0 = 5 bytes
    emit_line("@.str.false = private constant [6 x i8] c\"false\\00\"");       // false\0 = 6 bytes
    emit_line("@.str.space = private constant [2 x i8] c\" \\00\"");           // " "\0 = 2 bytes
    emit_line("@.str.newline = private constant [2 x i8] c\"\\0A\\00\"");      // \n\0 = 2 bytes
    emit_line("");
}

void LLVMIRGen::emit_module_lowlevel_decls() {
    // Emit declarations for lowlevel functions from imported modules
    if (!env_.module_registry()) {
        return;
    }

    emit_line("; Lowlevel functions from imported modules");

    // Get all modules from registry
    const auto& registry = env_.module_registry();
    const auto& all_modules = registry->get_all_modules();

    for (const auto& [module_name, module] : all_modules) {
        for (const auto& [func_name, func_sig] : module.functions) {
            if (func_sig.is_lowlevel) {
                // Generate LLVM declaration using semantic types
                std::string llvm_ret_type = llvm_type_from_semantic(func_sig.return_type);

                std::string params_str;
                for (size_t i = 0; i < func_sig.params.size(); ++i) {
                    if (i > 0)
                        params_str += ", ";
                    params_str += llvm_type_from_semantic(func_sig.params[i]);
                }

                // Sanitize function name: replace :: with _ for valid LLVM identifiers
                std::string sanitized_name = func_name;
                size_t pos = 0;
                while ((pos = sanitized_name.find("::", pos)) != std::string::npos) {
                    sanitized_name.replace(pos, 2, "_");
                    pos += 1;
                }

                // Emit declaration with tml_ prefix
                emit_line("declare " + llvm_ret_type + " @tml_" + sanitized_name + "(" +
                          params_str + ")");
            }
        }
    }

    emit_line("");
}

void LLVMIRGen::emit_module_pure_tml_functions() {
    // Emit LLVM IR for pure TML functions from imported modules
    if (!env_.module_registry()) {
        return;
    }

    const auto& registry = env_.module_registry();
    const auto& all_modules = registry->get_all_modules();

    // Collect imported module paths AND type names for filtering
    // This dramatically reduces codegen time by skipping unneeded modules
    std::unordered_set<std::string> imported_types;
    std::unordered_set<std::string> imported_module_paths;
    const auto& all_imports = env_.all_imports();
    for (const auto& [name, sym] : all_imports) {
        imported_types.insert(sym.original_name);
        imported_types.insert(name); // Also add local alias
        // Track the module path this symbol was imported from
        if (!sym.module_path.empty()) {
            imported_module_paths.insert(sym.module_path);
        }
    }

    emit_line("; Pure TML functions from imported modules");

    for (const auto& [module_name, module] : all_modules) {
        // Check if module has pure TML functions
        if (!module.has_pure_tml_functions || module.source_code.empty()) {
            continue;
        }

        // Early skip: Only process modules that were actually imported from
        // This avoids expensive re-parsing of modules we don't need
        if (!imported_module_paths.empty()) {
            bool should_process = false;

            // Check if this module path matches or is a parent of an imported module
            // e.g., if "std::sync::arc" is imported, process both "std::sync::arc" and "std::sync"
            for (const auto& imported_path : imported_module_paths) {
                // Exact match
                if (module_name == imported_path) {
                    should_process = true;
                    break;
                }
                // This module is a parent of an imported module
                // e.g., module_name="std::sync" and imported_path="std::sync::arc"
                if (imported_path.find(module_name + "::") == 0) {
                    should_process = true;
                    break;
                }
                // This module is a submodule of an imported module (rarely needed)
                // e.g., module_name="std::sync::arc::internal" and imported_path="std::sync::arc"
                if (module_name.find(imported_path + "::") == 0) {
                    should_process = true;
                    break;
                }
            }

            // Essential modules that are always needed (ordering, alloc, option)
            if (!should_process) {
                static const std::unordered_set<std::string> essential_modules = {
                    "core::ordering",    "core::alloc",      "core::option",       "core::types",
                    "std::sync::atomic", "std::sync::mutex", "std::sync::condvar",
                };
                // Check both full path and last segment for core modules
                should_process = essential_modules.count(module_name) > 0;
                if (!should_process) {
                    // Also check last segment for backwards compat with non-prefixed modules
                    std::string last_segment = module_name;
                    auto last_sep = module_name.rfind("::");
                    if (last_sep != std::string::npos) {
                        last_segment = module_name.substr(last_sep + 2);
                    }
                    static const std::unordered_set<std::string> essential_last_segments = {
                        "ordering",
                        "alloc",
                        "option",
                    };
                    should_process = essential_last_segments.count(last_segment) > 0;
                }
            }

            if (!should_process) {
                TML_DEBUG_LN("[MODULE] Early skip module: " << module_name);
                continue;
            }
        }

        // Check global AST cache first to avoid re-parsing library modules
        const parser::Module* cached_ast = nullptr;
        if (GlobalASTCache::should_cache(module_name)) {
            cached_ast = GlobalASTCache::instance().get(module_name);
        }

        const parser::Module* parsed_module_ptr = nullptr;
        auto mod_name = std::filesystem::path(module.file_path).stem().string();

        if (cached_ast) {
            // Use cached AST directly
            TML_DEBUG_LN("[CODEGEN] AST cache hit for: " << module_name);
            parsed_module_ptr = cached_ast;
        } else {
            // Parse the module source code
            auto source = lexer::Source::from_string(module.source_code, module.file_path);
            lexer::Lexer lex(source);
            auto tokens = lex.tokenize();

            if (lex.has_errors()) {
                continue; // Skip modules with lexer errors
            }

            parser::Parser parser(std::move(tokens));
            auto parse_result = parser.parse_module(mod_name);

            if (std::holds_alternative<std::vector<parser::ParseError>>(parse_result)) {
                continue; // Skip modules with parse errors
            }

            auto parsed_mod = std::get<parser::Module>(std::move(parse_result));

            // Store in global cache for library modules
            if (GlobalASTCache::should_cache(module_name)) {
                GlobalASTCache::instance().put(module_name, std::move(parsed_mod));
                // Get pointer from cache (now owns the AST)
                parsed_module_ptr = GlobalASTCache::instance().get(module_name);
                TML_DEBUG_LN("[CODEGEN] AST cached: " << module_name);
            } else {
                // For non-library modules, store locally
                imported_module_asts_.push_back(std::move(parsed_mod));
                parsed_module_ptr = &imported_module_asts_.back();
            }
        }

        if (!parsed_module_ptr) {
            continue; // Failed to get AST
        }

        const auto& parsed_module = *parsed_module_ptr;

        emit_line("; Module: " + module_name);

        // Set module prefix for function name generation
        // Replace :: with _ to create valid LLVM identifiers (e.g., core::alloc -> core_alloc)
        std::string sanitized_prefix = module_name;
        size_t pos = 0;
        while ((pos = sanitized_prefix.find("::", pos)) != std::string::npos) {
            sanitized_prefix.replace(pos, 2, "_");
            pos += 1;
        }
        current_module_prefix_ = sanitized_prefix;

        // Set submodule name for cross-module function lookups
        // For files like "unicode_data.tml", this allows lookups with "unicode_data::func"
        current_submodule_name_ = mod_name;

        // First pass: register struct/enum declarations (including generic ones)
        // IMPORTANT: Register ALL structs/enums, not just public ones!
        // Private types like StackNode[T] are still used internally and need to be
        // instantiated when size_of[T]() or similar intrinsics are called.
        for (const auto& decl : parsed_module.decls) {
            if (decl->is<parser::StructDecl>()) {
                const auto& s = decl->as<parser::StructDecl>();
                // Register all structs (public AND private) for generic instantiation
                // Private types are needed for internal use (e.g., size_of[StackNode[T]])
                gen_struct_decl(s);
            } else if (decl->is<parser::EnumDecl>()) {
                const auto& e = decl->as<parser::EnumDecl>();
                // Register all enums (public AND private) for generic instantiation
                gen_enum_decl(e);
            } else if (decl->is<parser::ConstDecl>()) {
                // Register module-level constants for use in functions
                const auto& const_decl = decl->as<parser::ConstDecl>();
                std::string value;

                // Support literal constants
                if (const_decl.value->is<parser::LiteralExpr>()) {
                    const auto& lit = const_decl.value->as<parser::LiteralExpr>();
                    if (lit.token.kind == lexer::TokenKind::IntLiteral) {
                        value = std::to_string(lit.token.int_value().value);
                    } else if (lit.token.kind == lexer::TokenKind::BoolLiteral) {
                        value = lit.token.bool_value() ? "1" : "0";
                    } else if (lit.token.kind == lexer::TokenKind::NullLiteral) {
                        value = "null";
                    }
                }
                // Support cast expressions (e.g., 14695981039346656037 as U64)
                else if (const_decl.value->is<parser::CastExpr>()) {
                    const auto& cast = const_decl.value->as<parser::CastExpr>();
                    if (cast.expr && cast.expr->is<parser::LiteralExpr>()) {
                        const auto& lit = cast.expr->as<parser::LiteralExpr>();
                        if (lit.token.kind == lexer::TokenKind::IntLiteral) {
                            value = std::to_string(lit.token.int_value().value);
                        }
                    } else if (cast.expr && cast.expr->is<parser::UnaryExpr>()) {
                        const auto& unary = cast.expr->as<parser::UnaryExpr>();
                        if (unary.op == parser::UnaryOp::Neg &&
                            unary.operand->is<parser::LiteralExpr>()) {
                            const auto& lit = unary.operand->as<parser::LiteralExpr>();
                            if (lit.token.kind == lexer::TokenKind::IntLiteral) {
                                int64_t int_val = static_cast<int64_t>(lit.token.int_value().value);
                                value = std::to_string(-int_val);
                            }
                        }
                    }
                }
                // Support unary expressions (e.g., -128)
                else if (const_decl.value->is<parser::UnaryExpr>()) {
                    const auto& unary = const_decl.value->as<parser::UnaryExpr>();
                    if (unary.op == parser::UnaryOp::Neg &&
                        unary.operand->is<parser::LiteralExpr>()) {
                        const auto& lit = unary.operand->as<parser::LiteralExpr>();
                        if (lit.token.kind == lexer::TokenKind::IntLiteral) {
                            int64_t int_val = static_cast<int64_t>(lit.token.int_value().value);
                            value = std::to_string(-int_val);
                        }
                    }
                }

                if (!value.empty()) {
                    std::string llvm_type = get_const_llvm_type(const_decl.type);
                    // Register both with and without module prefix
                    global_constants_[const_decl.name] = {value, llvm_type};
                    // Also register with qualified name for explicit lookups
                    std::string qualified_name = module_name + "::" + const_decl.name;
                    global_constants_[qualified_name] = {value, llvm_type};
                }
            } else if (decl->is<parser::UseDecl>()) {
                // Handle wildcard imports: "use module::*" brings all constants into scope
                const auto& use_decl = decl->as<parser::UseDecl>();
                if (use_decl.is_glob && !use_decl.path.segments.empty()) {
                    // Build the imported module path
                    std::string import_path;
                    for (size_t i = 0; i < use_decl.path.segments.size(); ++i) {
                        if (i > 0)
                            import_path += "::";
                        import_path += use_decl.path.segments[i];
                    }

                    // Look up the imported module and register its constants
                    auto imported_mod = registry->get_module(import_path);
                    if (imported_mod) {
                        // Import constants directly from the module
                        for (const auto& [const_name, const_info] : imported_mod->constants) {
                            // Only import non-qualified constants (not Type::CONST)
                            if (const_name.find("::") == std::string::npos) {
                                // Convert TML type to LLVM type
                                std::string llvm_type = llvm_type_name(const_info.tml_type);
                                global_constants_[const_name] = {const_info.value, llvm_type};
                                TML_DEBUG_LN("[MODULE] Imported constant via wildcard: "
                                             << const_name << " = " << const_info.value << " from "
                                             << import_path);
                            }
                        }

                        // Also follow re-exports (pub use) to import constants from
                        // re-exported modules. This handles chains like:
                        // std::zlib -> std::zlib::constants (via pub use zlib::constants::*)
                        for (const auto& re_export : imported_mod->re_exports) {
                            if (re_export.is_glob) {
                                auto re_exported_mod = registry->get_module(re_export.source_path);
                                if (re_exported_mod) {
                                    for (const auto& [const_name, const_info] :
                                         re_exported_mod->constants) {
                                        if (const_name.find("::") == std::string::npos) {
                                            std::string llvm_type =
                                                llvm_type_name(const_info.tml_type);
                                            global_constants_[const_name] = {const_info.value,
                                                                             llvm_type};
                                            TML_DEBUG_LN(
                                                "[MODULE] Imported constant via re-export: "
                                                << const_name << " = " << const_info.value
                                                << " from " << re_export.source_path);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        // 1.5 pass: pre-register ALL function signatures before generating any code
        // This ensures intra-module calls (like mod.tml calling unicode_data::func) resolve
        // correctly. Includes PRIVATE functions to support same-module calls.
        for (const auto& decl : parsed_module.decls) {
            if (decl->is<parser::FuncDecl>()) {
                const auto& func = decl->as<parser::FuncDecl>();
                // Pre-register both public AND private functions with bodies
                // This fixes intra-module calls to private helper functions
                if (!func.is_unsafe && func.body.has_value()) {
                    pre_register_func(func);
                }
            }
        }

        // Second pass: generate code for each function (both public AND private)
        for (const auto& decl : parsed_module.decls) {
            if (decl->is<parser::FuncDecl>()) {
                const auto& func = decl->as<parser::FuncDecl>();

                // Process extern functions - emit declarations
                if (func.extern_abi.has_value()) {
                    gen_func_decl(func);
                    continue;
                }

                // Generate code for both public AND private functions with bodies
                // Private functions are needed for intra-module helper functions
                if (!func.is_unsafe && func.body.has_value()) {
                    gen_func_decl(func);
                }
            }
            // Also handle impl blocks - generate methods for imported types
            else if (decl->is<parser::ImplDecl>()) {
                const auto& impl = decl->as<parser::ImplDecl>();

                // Register impl block for vtable generation (enables dyn dispatch)
                register_impl(&impl);

                // Skip generic impls - they need to be instantiated on demand
                // Generic impls have type parameters like impl[T] or impl[I: Iterator]
                if (!impl.generics.empty()) {
                    TML_DEBUG_LN("[MODULE] Skipping generic impl with " << impl.generics.size()
                                                                        << " type params");
                    continue;
                }

                // Get the type name for the impl
                std::string type_name;
                if (impl.self_type && impl.self_type->is<parser::NamedType>()) {
                    const auto& named = impl.self_type->as<parser::NamedType>();
                    if (!named.path.segments.empty()) {
                        type_name = named.path.segments.back();
                    }
                }

                // Skip impl blocks for types that aren't actually imported
                // This dramatically reduces codegen time (e.g., don't generate AtomicBool when only
                // Arc is used)
                if (!type_name.empty() && !imported_types.empty() &&
                    imported_types.find(type_name) == imported_types.end()) {
                    // Also check if it's a dependency type (e.g., Ordering is used by atomics)
                    // Skip filtering for common dependency types and primitive behaviors
                    static const std::unordered_set<std::string> always_generate = {
                        "Ordering",
                        "MutexGuard",
                        "RwLockReadGuard",
                        "RwLockWriteGuard",
                        "Weak", // Arc uses Weak
                        // Atomic types - needed by Arc, Mutex, and other sync primitives
                        "AtomicUsize",
                        "AtomicIsize",
                        "AtomicBool",
                        "AtomicI32",
                        "AtomicI64",
                        "AtomicU32",
                        "AtomicU64",
                        "AtomicPtr",
                        // Internal types used by sync primitives
                        "ArcInner",
                        "Layout",
                        "LayoutError",
                        // Sync primitives - needed by MPSC channels
                        "Mutex",
                        "Condvar",
                        "RawMutex",
                        "RawCondvar",
                    };
                    if (always_generate.find(type_name) == always_generate.end()) {
                        TML_DEBUG_LN("[MODULE] Skipping impl for non-imported type: " << type_name);
                        continue;
                    }
                }

                if (!type_name.empty()) {
                    // Extract constants from impl block (e.g., I32::MIN, I32::MAX)
                    for (const auto& const_decl : impl.constants) {
                        std::string qualified_name = type_name + "::" + const_decl.name;
                        std::string value;

                        // Support: literal constants
                        if (const_decl.value->is<parser::LiteralExpr>()) {
                            const auto& lit = const_decl.value->as<parser::LiteralExpr>();
                            if (lit.token.kind == lexer::TokenKind::IntLiteral) {
                                value = std::to_string(lit.token.int_value().value);
                            } else if (lit.token.kind == lexer::TokenKind::BoolLiteral) {
                                value = lit.token.bool_value() ? "1" : "0";
                            }
                        }
                        // Support: cast expressions (e.g., -2147483648 as I32)
                        else if (const_decl.value->is<parser::CastExpr>()) {
                            const auto& cast = const_decl.value->as<parser::CastExpr>();
                            if (cast.expr && cast.expr->is<parser::LiteralExpr>()) {
                                const auto& lit = cast.expr->as<parser::LiteralExpr>();
                                if (lit.token.kind == lexer::TokenKind::IntLiteral) {
                                    value = std::to_string(lit.token.int_value().value);
                                }
                            } else if (cast.expr && cast.expr->is<parser::UnaryExpr>()) {
                                const auto& unary = cast.expr->as<parser::UnaryExpr>();
                                if (unary.op == parser::UnaryOp::Neg &&
                                    unary.operand->is<parser::LiteralExpr>()) {
                                    const auto& lit = unary.operand->as<parser::LiteralExpr>();
                                    if (lit.token.kind == lexer::TokenKind::IntLiteral) {
                                        int64_t int_val =
                                            static_cast<int64_t>(lit.token.int_value().value);
                                        value = std::to_string(-int_val);
                                    }
                                }
                            }
                        }
                        // Support: unary expressions (e.g., -128)
                        else if (const_decl.value->is<parser::UnaryExpr>()) {
                            const auto& unary = const_decl.value->as<parser::UnaryExpr>();
                            if (unary.op == parser::UnaryOp::Neg &&
                                unary.operand->is<parser::LiteralExpr>()) {
                                const auto& lit = unary.operand->as<parser::LiteralExpr>();
                                if (lit.token.kind == lexer::TokenKind::IntLiteral) {
                                    int64_t int_val =
                                        static_cast<int64_t>(lit.token.int_value().value);
                                    value = std::to_string(-int_val);
                                }
                            } else if (unary.operand->is<parser::CastExpr>()) {
                                const auto& cast = unary.operand->as<parser::CastExpr>();
                                if (cast.expr && cast.expr->is<parser::LiteralExpr>()) {
                                    const auto& lit = cast.expr->as<parser::LiteralExpr>();
                                    if (lit.token.kind == lexer::TokenKind::IntLiteral) {
                                        int64_t int_val =
                                            static_cast<int64_t>(lit.token.int_value().value);
                                        value = std::to_string(-int_val);
                                    }
                                }
                            }
                        }

                        if (!value.empty()) {
                            std::string llvm_type = get_const_llvm_type(const_decl.type);
                            global_constants_[qualified_name] = {value, llvm_type};
                        }
                    }

                    // For generic types (like Maybe[T]), ensure the generic struct type exists
                    // This is needed because impl methods use the base type name
                    auto enum_it = pending_generic_enums_.find(type_name);
                    if (enum_it != pending_generic_enums_.end()) {
                        // Check if generic struct type already declared
                        if (struct_types_.find(type_name) == struct_types_.end()) {
                            // Emit generic type definition with i64 payload (fits all
                            // instantiations)
                            type_defs_buffer_ << "%struct." << type_name
                                              << " = type { i32, i64 }\n";
                            struct_types_[type_name] = "%struct." + type_name;
                        }
                    }

                    // First pass: pre-instantiate generic types used in method signatures
                    for (const auto& method : impl.methods) {
                        if (method.return_type.has_value()) {
                            const auto& ret_type = *method.return_type;
                            if (ret_type->is<parser::NamedType>()) {
                                const auto& named = ret_type->as<parser::NamedType>();
                                if (named.generics.has_value() && !named.generics->args.empty()) {
                                    // Check if this is a pending generic enum
                                    std::string base_name;
                                    if (!named.path.segments.empty()) {
                                        base_name = named.path.segments.back();
                                    }
                                    auto it = pending_generic_enums_.find(base_name);
                                    if (it != pending_generic_enums_.end()) {
                                        // Convert parser type args to semantic types
                                        std::vector<types::TypePtr> type_args;
                                        for (const auto& arg : named.generics->args) {
                                            if (arg.is_type()) {
                                                type_args.push_back(resolve_parser_type_with_subs(
                                                    *arg.as_type(), {}));
                                            }
                                        }
                                        // Check if already instantiated
                                        std::string mangled =
                                            mangle_struct_name(base_name, type_args);
                                        if (struct_types_.find(mangled) == struct_types_.end()) {
                                            gen_enum_instantiation(*it->second, type_args);
                                        }
                                    }
                                }
                            }
                        }
                    }

                    // Second pass: generate the methods
                    for (const auto& method : impl.methods) {
                        // Generate code for public, non-lowlevel methods with bodies
                        if (method.vis == parser::Visibility::Public && !method.is_unsafe &&
                            method.body.has_value()) {
                            // Generate impl method with qualified name
                            gen_impl_method(type_name, method);
                        }
                    }
                }
            }
        }

        // Clear module prefix after processing this module
        current_module_prefix_.clear();
    }

    emit_line("");
}

void LLVMIRGen::emit_string_constants() {
    if (string_literals_.empty())
        return;

    emit_line("; String constants");
    for (const auto& [name, value] : string_literals_) {
        // Escape the string and add null terminator
        std::string escaped;
        for (char c : value) {
            if (c == '\n')
                escaped += "\\0A";
            else if (c == '\t')
                escaped += "\\09";
            else if (c == '\\')
                escaped += "\\5C";
            else if (c == '"')
                escaped += "\\22";
            else
                escaped += c;
        }
        escaped += "\\00";

        emit_line(name + " = private constant [" + std::to_string(value.size() + 1) + " x i8] c\"" +
                  escaped + "\"");
    }
    emit_line("");
}

} // namespace tml::codegen
